package logic

import (
	"fmt"
	"strings"

	logic2 "github.com/w7panel/w7panel-zpk/common/logic"
	v1 "k8s.io/api/core/v1"
)

// traditionCodeInstallShell is an internal shell task generated by the
// packer.  The task runs in the selected environment's shared PVC mount; the
// mount path already includes the environment's domain, so the archive is
// extracted directly into that directory.
const traditionCodeInstallShell = `set -eu
code_install_path={{ printf "/www/wwwroot/%s" (include "tradition.codeInstallDirectory" .) | quote }}
code_package_url={{ .Values.tradition.codePackageUrl | quote }}
test -n "$code_package_url"
mkdir -p "$code_install_path"
tmp_zip="$(mktemp /tmp/tradition-code.XXXXXX)"
trap 'rm -f "$tmp_zip"' EXIT
wget -q -O "$tmp_zip" "$code_package_url"
unzip -oq "$tmp_zip" -d "$code_install_path"`

// environmentPodAffinityValues keeps workloads that use an environment's
// ReadWriteOnce storage on a node where that environment is running.
func environmentPodAffinityValues(identify string) map[string]interface{} {
	identify = strings.ToLower(strings.TrimSpace(strings.ReplaceAll(identify, "_", "-")))
	return map[string]interface{}{"podAffinity": map[string]interface{}{
		"requiredDuringSchedulingIgnoredDuringExecution": []interface{}{map[string]interface{}{
			"labelSelector": map[string]interface{}{"matchExpressions": []interface{}{map[string]interface{}{
				"key": "w7.cc/identifie", "operator": "In", "values": []string{identify},
			}}},
			"topologyKey": "kubernetes.io/hostname",
		}},
	}}
}

// withTraditionAppStorageClaimName resolves the empty claimName persisted by
// the editor. The selected environment release remains the source of truth
// for the concrete PVC name at Helm render time.
func withTraditionAppStorageClaimName(platform logic2.Platform) logic2.Platform {
	platform.Volumes = append([]v1.Volume(nil), platform.Volumes...)
	for index := range platform.Volumes {
		volume := &platform.Volumes[index]
		if volume.Name != environmentStorageVolumeName || volume.PersistentVolumeClaim == nil {
			continue
		}
		if volume.PersistentVolumeClaim.ClaimName == "" {
			volume.PersistentVolumeClaim.ClaimName = `{{ include "tradition.environmentStorageClaimName" . }}`
		}
	}
	return platform
}

func (hc *HelmPack) getTraditionShellJobContainerValues() map[string]interface{} {
	return map[string]interface{}{
		"name":  strings.ReplaceAll(hc.Manifest.Application.Identifie, "_", "-"),
		"image": imageValues(hc.getTraditionRuntimeImage(), v1.PullIfNotPresent), "env": []v1.EnvVar{},
		"resources":       v1.ResourceRequirements{},
		"volumeMounts":    []v1.VolumeMount{{Name: environmentStorageVolumeName, MountPath: "/www/wwwroot/{{ include \"tradition.codeInstallDirectory\" . }}", SubPath: "nginx-web-dir/{{ include \"tradition.codeInstallDirectory\" . }}"}},
		"securityContext": map[string]interface{}{},
	}
}

func (hc *HelmPack) addTraditionAppValues(values map[string]interface{}) error {
	if strings.TrimSpace(hc.Manifest.Platform.Tradition.EnvironmentName) == "" {
		return fmt.Errorf("传统应用必须指定环境应用")
	}
	if strings.TrimSpace(hc.Manifest.Platform.Tradition.EnvironmentVersion) == "" {
		return fmt.Errorf("传统应用必须指定环境应用版本")
	}
	if strings.TrimSpace(hc.Manifest.Source.Url) == "" {
		return fmt.Errorf("传统应用必须配置代码包")
	}
	codePackageURL := ""
	depot, _ := NewDepot()
	codePackageURL, _ = depot.GetFormulaBackendZipDownloadUrlByApplication(
		hc.Manifest.Application,
		strings.TrimPrefix(hc.Manifest.Source.Url, "file://"),
		false,
	)

	values["tradition"] = map[string]interface{}{
		"codePackageUrl":       codePackageURL,
		"affinity":             environmentPodAffinityValues(hc.Manifest.Platform.Tradition.EnvironmentName),
		"environmentIdentifie": hc.Manifest.Platform.Tradition.EnvironmentName,
	}
	return nil
}

func (hc *HelmPack) traditionAppHelmValuesOptions() helmValuesOptions {
	options := hc.defaultHelmValuesOptions()
	options.platform = withTraditionAppStorageClaimName(hc.Manifest.Platform)
	options.platform.Shells = hc.getTraditionAppShells()
	// Traditional application jobs run in the selected environment's
	// container and mount its ReadWriteOnce PVC. Schedule them alongside the
	// environment workload rather than the traditional release itself.
	options.jobAffinity = environmentPodAffinityValues(hc.Manifest.Platform.Tradition.EnvironmentName)
	options.addValues = hc.addTraditionAppValues
	options.shellJobContainerValues = func(logic2.Platform, string) map[string]interface{} {
		return hc.getTraditionShellJobContainerValues()
	}
	return options
}

func (hc *HelmPack) packTraditionApp(rootDir, templatesDir string) error {
	if err := hc.generateValuesYaml(rootDir, hc.traditionAppHelmValuesOptions()); err != nil {
		return err
	}
	if err := hc.generateHelpersTpl(templatesDir, hc.Manifest.Application.Identifie); err != nil {
		return err
	}
	return hc.generateTraditionAppTemplates(templatesDir)
}

func (hc *HelmPack) generateTraditionAppTemplates(rootDir string) error {
	if err := writeHelmTemplateFile(rootDir, "_tradition.tpl", "tradition-helpers.tpl"); err != nil {
		return err
	}
	return writeHelmTemplateFile(rootDir, "shell-job.yaml", "shell-job.yaml.tpl")
}

func (hc *HelmPack) getTraditionAppShells() []logic2.Shell {
	shells := append([]logic2.Shell(nil), hc.Manifest.Platform.Shells...)
	if strings.TrimSpace(hc.Manifest.Source.Url) != "" {
		// Keep the legacy installer lifecycle: one pre-install,pre-upgrade
		// hook with weight -3, rather than separate install/upgrade jobs.
		shells = append(shells, logic2.Shell{
			Title: "安装传统应用代码",
			Type:  "pre-install,pre-upgrade",
			Image: managedCodeInstallShellImage,
			Shell: traditionCodeInstallShell,
		})
	}
	if image := hc.getTraditionRuntimeImage(); image != "" {
		for index := range shells {
			if strings.TrimSpace(shells[index].Image) == "" {
				shells[index].Image = image
			}
		}
	}
	return shells
}

func (hc *HelmPack) getTraditionRuntimeImage() string {
	imageTemplate := strings.TrimSpace(hc.Manifest.Platform.Tradition.EnvironmentImageTemplate)
	if imageTemplate == "" {
		return ""
	}
	return strings.ReplaceAll(imageTemplate, "{version}", hc.Manifest.Platform.Tradition.EnvironmentVersion)
}
