package logic

import (
	"fmt"
	"strings"

	logic2 "github.com/w7panel/w7panel-zpk/common/logic"
	v1 "k8s.io/api/core/v1"
)

// traditionCodeInstallShell is an internal shell task generated by the
// packer.  The task runs in the selected environment's shared PVC mount; the
// mount path already includes the environment's domain, so the archive is
// extracted directly into that directory.
const traditionCodeInstallShell = `set -eu
code_install_path={{ print "/www/wwwroot/" (include "tradition.codeInstallDirectory" .) | quote }}
code_package_url={{ .Values.tradition.codePackageUrl | quote }}
test -n "$code_package_url"
mkdir -p "$code_install_path"
tmp_zip="$(mktemp /tmp/tradition-code.XXXXXX)"
trap 'rm -f "$tmp_zip"' EXIT
wget -q -O "$tmp_zip" "$code_package_url"
unzip -oq "$tmp_zip" -d "$code_install_path"`

// traditionCodeUninstallShell clears the site directory while keeping the
// subPath mount point itself. Removing the mount point directly would fail
// with "device or resource busy" inside the Job container.
const traditionCodeUninstallShell = `set -eu
code_install_path={{ print "/www/wwwroot/" (include "tradition.codeInstallDirectory" .) | quote }}
case "$code_install_path" in
  /www/wwwroot/?*) ;;
  *) echo "refusing to clean invalid traditional application path" >&2; exit 1 ;;
esac
if [ -d "$code_install_path" ]; then
  find "$code_install_path" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} \;
fi`

// environmentPodAffinityValues keeps workloads that use an environment's
// ReadWriteOnce storage on a node where that environment is running.
func environmentPodAffinityValues(identify string) map[string]interface{} {
	releaseName, identify := environmentPodAffinityTarget(identify)
	if releaseName == "" {
		return nil
	}
	return podAffinityByGroupName(releaseName, identify)
}

func environmentPodPreferredAffinityValues(identify string) map[string]interface{} {
	releaseName, identify := environmentPodAffinityTarget(identify)
	if releaseName == "" {
		return nil
	}
	return preferredPodAffinityByGroupName(releaseName, identify)
}

func environmentPodAffinityTarget(identify string) (string, string) {
	identify = strings.ToLower(strings.TrimSpace(strings.ReplaceAll(identify, "_", "-")))
	if identify == "" {
		return "", ""
	}
	// Traditional applications are installed as a separate Helm release from
	// the selected environment.  The hidden dependency start parameter carries
	// that concrete release name at install time (and can differ for every
	// environment instance), so do not match by the artifact identifier.
	paramName := strings.ToUpper(strings.NewReplacer("-", "_", ".", "_").Replace(identify)) + dependencyReleaseNameSuffix
	releaseName := fmt.Sprintf(`{{ default %q (index .Values %q) }}`, identify, paramName)
	return releaseName, identify
}

// withTraditionAppStorageClaimName resolves the empty claimName persisted by
// the editor. The selected environment release remains the source of truth
// for the concrete PVC name at Helm render time.
func withTraditionAppStorageClaimName(platform logic2.Platform) logic2.Platform {
	platform.Volumes = append([]v1.Volume(nil), platform.Volumes...)
	for index := range platform.Volumes {
		volume := &platform.Volumes[index]
		if volume.Name != environmentStorageVolumeName || volume.PersistentVolumeClaim == nil {
			continue
		}
		if volume.PersistentVolumeClaim.ClaimName == "" {
			volume.PersistentVolumeClaim.ClaimName = `{{ include "tradition.environmentStorageClaimName" . }}`
		}
	}
	return platform
}

func (hc *HelmPack) getTraditionShellJobContainerValues() map[string]interface{} {
	return map[string]interface{}{
		"name":  strings.ReplaceAll(hc.Manifest.Application.Identifie, "_", "-"),
		"image": imageValues(hc.getTraditionRuntimeImage(), v1.PullIfNotPresent), "env": []v1.EnvVar{},
		"resources":       v1.ResourceRequirements{},
		"volumeMounts":    []v1.VolumeMount{{Name: environmentStorageVolumeName, MountPath: "/www/wwwroot/{{ include \"tradition.codeInstallDirectory\" . }}", SubPath: "nginx-web-dir/{{ include \"tradition.codeInstallDirectory\" . }}"}},
		"securityContext": map[string]interface{}{},
	}
}

func (hc *HelmPack) addTraditionAppValues(values map[string]interface{}) error {
	if strings.TrimSpace(hc.Manifest.Platform.Tradition.EnvironmentName) == "" {
		return fmt.Errorf("传统应用必须指定环境应用")
	}
	if strings.TrimSpace(hc.Manifest.Platform.Tradition.EnvironmentVersion) == "" {
		return fmt.Errorf("传统应用必须指定环境应用版本")
	}
	if strings.TrimSpace(hc.Manifest.Source.Url) == "" {
		return fmt.Errorf("传统应用必须配置代码包")
	}
	codePackageURL := ""
	depot, _ := NewDepot()
	codePackageURL, _ = depot.GetFormulaBackendZipDownloadUrlByApplication(
		hc.Manifest.Application,
		strings.TrimPrefix(hc.Manifest.Source.Url, "file://"),
		false,
	)

	values["tradition"] = map[string]interface{}{
		"codePackageUrl":       codePackageURL,
		"environmentIdentifie": hc.Manifest.Platform.Tradition.EnvironmentName,
	}
	return nil
}

func (hc *HelmPack) traditionAppHelmValuesOptions() helmValuesOptions {
	options := hc.defaultHelmValuesOptions()
	options.platform = withTraditionAppStorageClaimName(hc.Manifest.Platform)
	options.platform.Shells = hc.getTraditionAppShells()
	// Traditional application jobs run in the selected environment's
	// container and mount its ReadWriteOnce PVC. Schedule them alongside the
	// environment workload rather than the traditional release itself.
	options.jobAffinity = environmentPodAffinityValues(hc.Manifest.Platform.Tradition.EnvironmentName)
	options.jobPreferredAffinity = environmentPodPreferredAffinityValues(hc.Manifest.Platform.Tradition.EnvironmentName)
	options.addValues = hc.addTraditionAppValues
	options.shellJobContainerValues = func(logic2.Platform, string) map[string]interface{} {
		return hc.getTraditionShellJobContainerValues()
	}
	return options
}

func (hc *HelmPack) packTraditionApp(rootDir, templatesDir string) error {
	if err := hc.generateValuesYaml(rootDir, hc.traditionAppHelmValuesOptions()); err != nil {
		return err
	}
	if err := hc.generateHelpersTpl(templatesDir, hc.Manifest.Application.Identifie); err != nil {
		return err
	}
	return hc.generateTraditionAppTemplates(templatesDir)
}

func (hc *HelmPack) generateTraditionAppTemplates(rootDir string) error {
	if err := writeHelmTemplateFile(rootDir, "_tradition.tpl", "tradition-helpers.tpl"); err != nil {
		return err
	}
	return writeHelmTemplateFile(rootDir, "shell-job.yaml", "shell-job.yaml.tpl")
}

func (hc *HelmPack) getTraditionAppShells() []logic2.Shell {
	shells := append([]logic2.Shell(nil), hc.Manifest.Platform.Shells...)
	if strings.TrimSpace(hc.Manifest.Source.Url) != "" {
		// Keep one highest-priority pre-install,pre-upgrade hook rather than
		// separate install/upgrade jobs.
		shells = append(shells, logic2.Shell{
			Title: "安装传统应用代码",
			Type:  "pre-install,pre-upgrade",
			Image: managedCodeInstallShellImage,
			Shell: traditionCodeInstallShell,
		}, logic2.Shell{
			Title: "卸载传统应用代码",
			Type:  "uninstall",
			Image: managedCodeInstallShellImage,
			Shell: traditionCodeUninstallShell,
		})
	}
	if image := hc.getTraditionRuntimeImage(); image != "" {
		for index := range shells {
			if strings.TrimSpace(shells[index].Image) == "" {
				shells[index].Image = image
			}
		}
	}
	return shells
}

func (hc *HelmPack) getTraditionRuntimeImage() string {
	imageTemplate := strings.TrimSpace(hc.Manifest.Platform.Tradition.EnvironmentImageTemplate)
	if imageTemplate == "" {
		return ""
	}
	return strings.ReplaceAll(imageTemplate, "{version}", hc.Manifest.Platform.Tradition.EnvironmentVersion)
}
