package helm

import (
	"fmt"
	"strings"

	formulalogic "github.com/w7panel/w7panel-zpk/app/respo/logic/formula"
	logic2 "github.com/w7panel/w7panel-zpk/common/logic"
	v1 "k8s.io/api/core/v1"
)

// pluginCodeInstallShell is an internal shell task generated by the
// packer. The task runs in the selected traditional application's shared PVC
// mount; the mount path already includes the application's domain, so the archive is
// extracted directly into that directory.
const pluginCodeInstallShell = `set -eu
code_install_path={{ print "/www/wwwroot/" (include "plugin.codeInstallDirectory" .) | quote }}
code_package_url={{ .Values.plugin.codePackageUrl | quote }}
test -n "$code_package_url"
mkdir -p "$code_install_path"
tmp_zip="$(mktemp /tmp/plugin-code.XXXXXX)"
trap 'rm -f "$tmp_zip"' EXIT
wget -q -O "$tmp_zip" "$code_package_url"
unzip -oq "$tmp_zip" -d "$code_install_path"`

// pluginCodeUninstallShell clears the site directory while keeping the
// subPath mount point itself. Removing the mount point directly would fail
// with "device or resource busy" inside the Job container.
const pluginCodeUninstallShell = `set -eu
code_install_path={{ print "/www/wwwroot/" (include "plugin.codeInstallDirectory" .) | quote }}
case "$code_install_path" in
  /www/wwwroot/?*) ;;
  *) echo "refusing to clean invalid traditional application path" >&2; exit 1 ;;
esac
if [ -d "$code_install_path" ]; then
  find "$code_install_path" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} \;
fi`

// pluginPodAffinityValues keeps plugin workloads that use a traditional
// application's ReadWriteOnce storage on the same node as that application.
func pluginPodAffinityValues(identify string) map[string]interface{} {
	releaseName, identify := pluginPodAffinityTarget(identify)
	if releaseName == "" {
		return nil
	}
	return podAffinityByGroupName(releaseName, identify)
}

func pluginPodPreferredAffinityValues(identify string) map[string]interface{} {
	releaseName, identify := pluginPodAffinityTarget(identify)
	if releaseName == "" {
		return nil
	}
	return preferredPodAffinityByGroupName(releaseName, identify)
}

func pluginPodAffinityTarget(identify string) (string, string) {
	identify = strings.ToLower(strings.TrimSpace(strings.ReplaceAll(identify, "_", "-")))
	if identify == "" {
		return "", ""
	}
	// Plugins are installed as a separate Helm release from the selected
	// traditional application. The hidden dependency start parameter carries
	// that concrete release name at install time (and can differ for every
	// traditional application instance), so do not match by the artifact identifier.
	paramName := strings.ToUpper(strings.NewReplacer("-", "_", ".", "_").Replace(identify)) + formulalogic.DependencyReleaseNameSuffix
	releaseName := fmt.Sprintf(`{{ default %q (index .Values %q) }}`, identify, paramName)
	return releaseName, identify
}

// withPluginAppStorageClaimName resolves the empty claimName persisted by
// the editor. The selected traditional application release remains the source of truth
// for the concrete PVC name at Helm render time.
func withPluginAppStorageClaimName(platform logic2.Platform) logic2.Platform {
	platform.Volumes = append([]v1.Volume(nil), platform.Volumes...)
	for index := range platform.Volumes {
		volume := &platform.Volumes[index]
		if volume.Name != traditionStorageVolumeName || volume.PersistentVolumeClaim == nil {
			continue
		}
		if volume.PersistentVolumeClaim.ClaimName == "" {
			volume.PersistentVolumeClaim.ClaimName = `{{ include "plugin.traditionStorageClaimName" . }}`
		}
	}
	return platform
}

func (hc *HelmPack) getPluginShellJobContainerValues() map[string]interface{} {
	return map[string]interface{}{
		"name":  strings.ReplaceAll(hc.Manifest.Application.Identifie, "_", "-"),
		"image": imageValues(hc.getPluginRuntimeImage(), v1.PullIfNotPresent), "env": []v1.EnvVar{},
		"resources":       v1.ResourceRequirements{},
		"volumeMounts":    []v1.VolumeMount{{Name: traditionStorageVolumeName, MountPath: "/www/wwwroot/{{ include \"plugin.codeInstallDirectory\" . }}", SubPath: "nginx-web-dir/{{ include \"plugin.codeInstallDirectory\" . }}"}},
		"securityContext": map[string]interface{}{},
	}
}

func (hc *HelmPack) addPluginAppValues(values map[string]interface{}) error {
	plugin := hc.pluginConfig()
	if strings.TrimSpace(plugin.TraditionName) == "" {
		return fmt.Errorf("应用插件必须指定传统应用")
	}
	if strings.TrimSpace(plugin.TraditionVersion) == "" {
		return fmt.Errorf("应用插件必须指定传统应用版本")
	}
	if strings.TrimSpace(hc.Manifest.Source.Url) == "" {
		return fmt.Errorf("应用插件必须配置代码包")
	}
	codePackageURL := ""
	depot, _ := formulalogic.NewDepot()
	codePackageURL, _ = depot.GetFormulaBackendZipDownloadUrlByApplication(
		hc.Manifest.Application,
		strings.TrimPrefix(hc.Manifest.Source.Url, "file://"),
		false,
	)

	values["plugin"] = map[string]interface{}{
		"codePackageUrl":     codePackageURL,
		"traditionIdentifie": plugin.TraditionName,
	}
	return nil
}

func (hc *HelmPack) pluginAppHelmValuesOptions() helmValuesOptions {
	plugin := hc.pluginConfig()
	options := hc.defaultHelmValuesOptions()
	options.platform = withPluginAppStorageClaimName(hc.Manifest.Platform)
	options.platform.Shells = hc.getPluginAppShells()
	// Plugin jobs run in the selected traditional application's
	// container and mount its ReadWriteOnce PVC. Schedule them alongside the
	// traditional application workload rather than the plugin release itself.
	options.jobAffinity = pluginPodAffinityValues(plugin.TraditionName)
	options.jobPreferredAffinity = pluginPodPreferredAffinityValues(plugin.TraditionName)
	options.addValues = hc.addPluginAppValues
	options.shellJobContainerValues = func(logic2.Platform, string) map[string]interface{} {
		return hc.getPluginShellJobContainerValues()
	}
	return options
}

func (hc *HelmPack) packPluginApp(rootDir, templatesDir string) error {
	if err := hc.generateValuesYaml(rootDir, hc.pluginAppHelmValuesOptions()); err != nil {
		return err
	}
	if err := hc.generateHelpersTpl(templatesDir, hc.Manifest.Application.Identifie); err != nil {
		return err
	}
	return hc.generatePluginAppTemplates(templatesDir)
}

func (hc *HelmPack) generatePluginAppTemplates(rootDir string) error {
	if err := writeHelmTemplateFile(rootDir, "_plugin.tpl", "plugin-helpers.tpl"); err != nil {
		return err
	}
	return writeHelmTemplateFile(rootDir, "shell-job.yaml", "shell-job.yaml.tpl")
}

func (hc *HelmPack) getPluginAppShells() []logic2.Shell {
	shells := append([]logic2.Shell(nil), hc.Manifest.Platform.Shells...)
	if strings.TrimSpace(hc.Manifest.Source.Url) != "" {
		// Keep one highest-priority pre-install,pre-upgrade hook rather than
		// separate install/upgrade jobs.
		shells = append(shells, logic2.Shell{
			Title: "安装应用插件代码",
			Type:  "pre-install,pre-upgrade",
			Image: managedCodeInstallShellImage,
			Shell: pluginCodeInstallShell,
		}, logic2.Shell{
			Title: "卸载应用插件代码",
			Type:  "uninstall",
			Image: managedCodeInstallShellImage,
			Shell: pluginCodeUninstallShell,
		})
	}
	if image := hc.getPluginRuntimeImage(); image != "" {
		for index := range shells {
			if strings.TrimSpace(shells[index].Image) == "" {
				shells[index].Image = image
			}
		}
	}
	return shells
}

func (hc *HelmPack) getPluginRuntimeImage() string {
	plugin := hc.pluginConfig()
	imageTemplate := strings.TrimSpace(plugin.TraditionImageTemplate)
	if imageTemplate == "" {
		return ""
	}
	return strings.ReplaceAll(imageTemplate, "{version}", plugin.TraditionVersion)
}

func (hc *HelmPack) pluginConfig() logic2.Plugin {
	if hc.Manifest.Platform.Plugin == nil {
		return logic2.Plugin{}
	}
	return *hc.Manifest.Platform.Plugin
}
