apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zpk.storageClaimName" . }}
  labels:
    {{- include "zpk.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.global.cluster.storageRWMode }}
  storageClassName: {{ .Values.global.cluster.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.global.zpk.storageSize | quote }}
