// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                                    = new(Query)
	Formula                              *formula
	Order                                *order
	RegistryNamespace                    *registryNamespace
	RegistryRepository                   *registryRepository
	RegistryRepositoryDeployRule         *registryRepositoryDeployRule
	RegistryRepositoryDeployRuleMatchLog *registryRepositoryDeployRuleMatchLog
	RegistryRepositoryTag                *registryRepositoryTag
	RegistryUser                         *registryUser
	RegistryUserPermission               *registryUserPermission
	Tag                                  *tag
	TagFormula                           *tagFormula
	Version                              *version
	W7panelUser                          *w7panelUser
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Formula = &Q.Formula
	Order = &Q.Order
	RegistryNamespace = &Q.RegistryNamespace
	RegistryRepository = &Q.RegistryRepository
	RegistryRepositoryDeployRule = &Q.RegistryRepositoryDeployRule
	RegistryRepositoryDeployRuleMatchLog = &Q.RegistryRepositoryDeployRuleMatchLog
	RegistryRepositoryTag = &Q.RegistryRepositoryTag
	RegistryUser = &Q.RegistryUser
	RegistryUserPermission = &Q.RegistryUserPermission
	Tag = &Q.Tag
	TagFormula = &Q.TagFormula
	Version = &Q.Version
	W7panelUser = &Q.W7panelUser
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                                   db,
		Formula:                              newFormula(db, opts...),
		Order:                                newOrder(db, opts...),
		RegistryNamespace:                    newRegistryNamespace(db, opts...),
		RegistryRepository:                   newRegistryRepository(db, opts...),
		RegistryRepositoryDeployRule:         newRegistryRepositoryDeployRule(db, opts...),
		RegistryRepositoryDeployRuleMatchLog: newRegistryRepositoryDeployRuleMatchLog(db, opts...),
		RegistryRepositoryTag:                newRegistryRepositoryTag(db, opts...),
		RegistryUser:                         newRegistryUser(db, opts...),
		RegistryUserPermission:               newRegistryUserPermission(db, opts...),
		Tag:                                  newTag(db, opts...),
		TagFormula:                           newTagFormula(db, opts...),
		Version:                              newVersion(db, opts...),
		W7panelUser:                          newW7panelUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Formula                              formula
	Order                                order
	RegistryNamespace                    registryNamespace
	RegistryRepository                   registryRepository
	RegistryRepositoryDeployRule         registryRepositoryDeployRule
	RegistryRepositoryDeployRuleMatchLog registryRepositoryDeployRuleMatchLog
	RegistryRepositoryTag                registryRepositoryTag
	RegistryUser                         registryUser
	RegistryUserPermission               registryUserPermission
	Tag                                  tag
	TagFormula                           tagFormula
	Version                              version
	W7panelUser                          w7panelUser
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                                   db,
		Formula:                              q.Formula.clone(db),
		Order:                                q.Order.clone(db),
		RegistryNamespace:                    q.RegistryNamespace.clone(db),
		RegistryRepository:                   q.RegistryRepository.clone(db),
		RegistryRepositoryDeployRule:         q.RegistryRepositoryDeployRule.clone(db),
		RegistryRepositoryDeployRuleMatchLog: q.RegistryRepositoryDeployRuleMatchLog.clone(db),
		RegistryRepositoryTag:                q.RegistryRepositoryTag.clone(db),
		RegistryUser:                         q.RegistryUser.clone(db),
		RegistryUserPermission:               q.RegistryUserPermission.clone(db),
		Tag:                                  q.Tag.clone(db),
		TagFormula:                           q.TagFormula.clone(db),
		Version:                              q.Version.clone(db),
		W7panelUser:                          q.W7panelUser.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                                   db,
		Formula:                              q.Formula.replaceDB(db),
		Order:                                q.Order.replaceDB(db),
		RegistryNamespace:                    q.RegistryNamespace.replaceDB(db),
		RegistryRepository:                   q.RegistryRepository.replaceDB(db),
		RegistryRepositoryDeployRule:         q.RegistryRepositoryDeployRule.replaceDB(db),
		RegistryRepositoryDeployRuleMatchLog: q.RegistryRepositoryDeployRuleMatchLog.replaceDB(db),
		RegistryRepositoryTag:                q.RegistryRepositoryTag.replaceDB(db),
		RegistryUser:                         q.RegistryUser.replaceDB(db),
		RegistryUserPermission:               q.RegistryUserPermission.replaceDB(db),
		Tag:                                  q.Tag.replaceDB(db),
		TagFormula:                           q.TagFormula.replaceDB(db),
		Version:                              q.Version.replaceDB(db),
		W7panelUser:                          q.W7panelUser.replaceDB(db),
	}
}

type queryCtx struct {
	Formula                              IFormulaDo
	Order                                IOrderDo
	RegistryNamespace                    IRegistryNamespaceDo
	RegistryRepository                   IRegistryRepositoryDo
	RegistryRepositoryDeployRule         IRegistryRepositoryDeployRuleDo
	RegistryRepositoryDeployRuleMatchLog IRegistryRepositoryDeployRuleMatchLogDo
	RegistryRepositoryTag                IRegistryRepositoryTagDo
	RegistryUser                         IRegistryUserDo
	RegistryUserPermission               IRegistryUserPermissionDo
	Tag                                  ITagDo
	TagFormula                           ITagFormulaDo
	Version                              IVersionDo
	W7panelUser                          IW7panelUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Formula:                              q.Formula.WithContext(ctx),
		Order:                                q.Order.WithContext(ctx),
		RegistryNamespace:                    q.RegistryNamespace.WithContext(ctx),
		RegistryRepository:                   q.RegistryRepository.WithContext(ctx),
		RegistryRepositoryDeployRule:         q.RegistryRepositoryDeployRule.WithContext(ctx),
		RegistryRepositoryDeployRuleMatchLog: q.RegistryRepositoryDeployRuleMatchLog.WithContext(ctx),
		RegistryRepositoryTag:                q.RegistryRepositoryTag.WithContext(ctx),
		RegistryUser:                         q.RegistryUser.WithContext(ctx),
		RegistryUserPermission:               q.RegistryUserPermission.WithContext(ctx),
		Tag:                                  q.Tag.WithContext(ctx),
		TagFormula:                           q.TagFormula.WithContext(ctx),
		Version:                              q.Version.WithContext(ctx),
		W7panelUser:                          q.W7panelUser.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
