// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-zpk/common/entity"
)

func newW7panelUser(db *gorm.DB, opts ...gen.DOOption) w7panelUser {
	_w7panelUser := w7panelUser{}

	_w7panelUser.w7panelUserDo.UseDB(db, opts...)
	_w7panelUser.w7panelUserDo.UseModel(&entity.W7panelUser{})

	tableName := _w7panelUser.w7panelUserDo.TableName()
	_w7panelUser.ALL = field.NewAsterisk(tableName)
	_w7panelUser.ID = field.NewInt32(tableName, "id")
	_w7panelUser.W7panelUID = field.NewString(tableName, "w7panel_uid")
	_w7panelUser.W7panelUsername = field.NewString(tableName, "w7panel_username")
	_w7panelUser.UserUID = field.NewInt32(tableName, "user_uid")
	_w7panelUser.CreatedAt = field.NewTime(tableName, "created_at")
	_w7panelUser.UpdatedAt = field.NewTime(tableName, "updated_at")

	_w7panelUser.fillFieldMap()

	return _w7panelUser
}

type w7panelUser struct {
	w7panelUserDo

	ALL             field.Asterisk
	ID              field.Int32
	W7panelUID      field.String
	W7panelUsername field.String
	UserUID         field.Int32
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (w w7panelUser) Table(newTableName string) *w7panelUser {
	w.w7panelUserDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w w7panelUser) As(alias string) *w7panelUser {
	w.w7panelUserDo.DO = *(w.w7panelUserDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *w7panelUser) updateTableName(table string) *w7panelUser {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt32(table, "id")
	w.W7panelUID = field.NewString(table, "w7panel_uid")
	w.W7panelUsername = field.NewString(table, "w7panel_username")
	w.UserUID = field.NewInt32(table, "user_uid")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *w7panelUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *w7panelUser) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 6)
	w.fieldMap["id"] = w.ID
	w.fieldMap["w7panel_uid"] = w.W7panelUID
	w.fieldMap["w7panel_username"] = w.W7panelUsername
	w.fieldMap["user_uid"] = w.UserUID
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w w7panelUser) clone(db *gorm.DB) w7panelUser {
	w.w7panelUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w w7panelUser) replaceDB(db *gorm.DB) w7panelUser {
	w.w7panelUserDo.ReplaceDB(db)
	return w
}

type w7panelUserDo struct{ gen.DO }

type IW7panelUserDo interface {
	gen.SubQuery
	Debug() IW7panelUserDo
	WithContext(ctx context.Context) IW7panelUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IW7panelUserDo
	WriteDB() IW7panelUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IW7panelUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IW7panelUserDo
	Not(conds ...gen.Condition) IW7panelUserDo
	Or(conds ...gen.Condition) IW7panelUserDo
	Select(conds ...field.Expr) IW7panelUserDo
	Where(conds ...gen.Condition) IW7panelUserDo
	Order(conds ...field.Expr) IW7panelUserDo
	Distinct(cols ...field.Expr) IW7panelUserDo
	Omit(cols ...field.Expr) IW7panelUserDo
	Join(table schema.Tabler, on ...field.Expr) IW7panelUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IW7panelUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IW7panelUserDo
	Group(cols ...field.Expr) IW7panelUserDo
	Having(conds ...gen.Condition) IW7panelUserDo
	Limit(limit int) IW7panelUserDo
	Offset(offset int) IW7panelUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IW7panelUserDo
	Unscoped() IW7panelUserDo
	Create(values ...*entity.W7panelUser) error
	CreateInBatches(values []*entity.W7panelUser, batchSize int) error
	Save(values ...*entity.W7panelUser) error
	First() (*entity.W7panelUser, error)
	Take() (*entity.W7panelUser, error)
	Last() (*entity.W7panelUser, error)
	Find() ([]*entity.W7panelUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.W7panelUser, err error)
	FindInBatches(result *[]*entity.W7panelUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.W7panelUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IW7panelUserDo
	Assign(attrs ...field.AssignExpr) IW7panelUserDo
	Joins(fields ...field.RelationField) IW7panelUserDo
	Preload(fields ...field.RelationField) IW7panelUserDo
	FirstOrInit() (*entity.W7panelUser, error)
	FirstOrCreate() (*entity.W7panelUser, error)
	FindByPage(offset int, limit int) (result []*entity.W7panelUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IW7panelUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w w7panelUserDo) Debug() IW7panelUserDo {
	return w.withDO(w.DO.Debug())
}

func (w w7panelUserDo) WithContext(ctx context.Context) IW7panelUserDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w w7panelUserDo) ReadDB() IW7panelUserDo {
	return w.Clauses(dbresolver.Read)
}

func (w w7panelUserDo) WriteDB() IW7panelUserDo {
	return w.Clauses(dbresolver.Write)
}

func (w w7panelUserDo) Session(config *gorm.Session) IW7panelUserDo {
	return w.withDO(w.DO.Session(config))
}

func (w w7panelUserDo) Clauses(conds ...clause.Expression) IW7panelUserDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w w7panelUserDo) Returning(value interface{}, columns ...string) IW7panelUserDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w w7panelUserDo) Not(conds ...gen.Condition) IW7panelUserDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w w7panelUserDo) Or(conds ...gen.Condition) IW7panelUserDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w w7panelUserDo) Select(conds ...field.Expr) IW7panelUserDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w w7panelUserDo) Where(conds ...gen.Condition) IW7panelUserDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w w7panelUserDo) Order(conds ...field.Expr) IW7panelUserDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w w7panelUserDo) Distinct(cols ...field.Expr) IW7panelUserDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w w7panelUserDo) Omit(cols ...field.Expr) IW7panelUserDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w w7panelUserDo) Join(table schema.Tabler, on ...field.Expr) IW7panelUserDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w w7panelUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IW7panelUserDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w w7panelUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IW7panelUserDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w w7panelUserDo) Group(cols ...field.Expr) IW7panelUserDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w w7panelUserDo) Having(conds ...gen.Condition) IW7panelUserDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w w7panelUserDo) Limit(limit int) IW7panelUserDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w w7panelUserDo) Offset(offset int) IW7panelUserDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w w7panelUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IW7panelUserDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w w7panelUserDo) Unscoped() IW7panelUserDo {
	return w.withDO(w.DO.Unscoped())
}

func (w w7panelUserDo) Create(values ...*entity.W7panelUser) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w w7panelUserDo) CreateInBatches(values []*entity.W7panelUser, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w w7panelUserDo) Save(values ...*entity.W7panelUser) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w w7panelUserDo) First() (*entity.W7panelUser, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.W7panelUser), nil
	}
}

func (w w7panelUserDo) Take() (*entity.W7panelUser, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.W7panelUser), nil
	}
}

func (w w7panelUserDo) Last() (*entity.W7panelUser, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.W7panelUser), nil
	}
}

func (w w7panelUserDo) Find() ([]*entity.W7panelUser, error) {
	result, err := w.DO.Find()
	return result.([]*entity.W7panelUser), err
}

func (w w7panelUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.W7panelUser, err error) {
	buf := make([]*entity.W7panelUser, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w w7panelUserDo) FindInBatches(result *[]*entity.W7panelUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w w7panelUserDo) Attrs(attrs ...field.AssignExpr) IW7panelUserDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w w7panelUserDo) Assign(attrs ...field.AssignExpr) IW7panelUserDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w w7panelUserDo) Joins(fields ...field.RelationField) IW7panelUserDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w w7panelUserDo) Preload(fields ...field.RelationField) IW7panelUserDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w w7panelUserDo) FirstOrInit() (*entity.W7panelUser, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.W7panelUser), nil
	}
}

func (w w7panelUserDo) FirstOrCreate() (*entity.W7panelUser, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.W7panelUser), nil
	}
}

func (w w7panelUserDo) FindByPage(offset int, limit int) (result []*entity.W7panelUser, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w w7panelUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w w7panelUserDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w w7panelUserDo) Delete(models ...*entity.W7panelUser) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *w7panelUserDo) withDO(do gen.Dao) *w7panelUserDo {
	w.DO = *do.(*gen.DO)
	return w
}
