// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-zpk/common/entity"
)

func newRegistryUserPermission(db *gorm.DB, opts ...gen.DOOption) registryUserPermission {
	_registryUserPermission := registryUserPermission{}

	_registryUserPermission.registryUserPermissionDo.UseDB(db, opts...)
	_registryUserPermission.registryUserPermissionDo.UseModel(&entity.RegistryUserPermission{})

	tableName := _registryUserPermission.registryUserPermissionDo.TableName()
	_registryUserPermission.ALL = field.NewAsterisk(tableName)
	_registryUserPermission.ID = field.NewInt32(tableName, "id")
	_registryUserPermission.UserID = field.NewInt32(tableName, "user_id")
	_registryUserPermission.ResourceValue = field.NewString(tableName, "resource_value")
	_registryUserPermission.ResourceType = field.NewString(tableName, "resource_type")
	_registryUserPermission.Action = field.NewField(tableName, "action")
	_registryUserPermission.CreatedAt = field.NewTime(tableName, "created_at")

	_registryUserPermission.fillFieldMap()

	return _registryUserPermission
}

type registryUserPermission struct {
	registryUserPermissionDo

	ALL           field.Asterisk
	ID            field.Int32
	UserID        field.Int32
	ResourceValue field.String
	ResourceType  field.String
	Action        field.Field
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (r registryUserPermission) Table(newTableName string) *registryUserPermission {
	r.registryUserPermissionDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r registryUserPermission) As(alias string) *registryUserPermission {
	r.registryUserPermissionDo.DO = *(r.registryUserPermissionDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *registryUserPermission) updateTableName(table string) *registryUserPermission {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.UserID = field.NewInt32(table, "user_id")
	r.ResourceValue = field.NewString(table, "resource_value")
	r.ResourceType = field.NewString(table, "resource_type")
	r.Action = field.NewField(table, "action")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *registryUserPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *registryUserPermission) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["resource_value"] = r.ResourceValue
	r.fieldMap["resource_type"] = r.ResourceType
	r.fieldMap["action"] = r.Action
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r registryUserPermission) clone(db *gorm.DB) registryUserPermission {
	r.registryUserPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r registryUserPermission) replaceDB(db *gorm.DB) registryUserPermission {
	r.registryUserPermissionDo.ReplaceDB(db)
	return r
}

type registryUserPermissionDo struct{ gen.DO }

type IRegistryUserPermissionDo interface {
	gen.SubQuery
	Debug() IRegistryUserPermissionDo
	WithContext(ctx context.Context) IRegistryUserPermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRegistryUserPermissionDo
	WriteDB() IRegistryUserPermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRegistryUserPermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRegistryUserPermissionDo
	Not(conds ...gen.Condition) IRegistryUserPermissionDo
	Or(conds ...gen.Condition) IRegistryUserPermissionDo
	Select(conds ...field.Expr) IRegistryUserPermissionDo
	Where(conds ...gen.Condition) IRegistryUserPermissionDo
	Order(conds ...field.Expr) IRegistryUserPermissionDo
	Distinct(cols ...field.Expr) IRegistryUserPermissionDo
	Omit(cols ...field.Expr) IRegistryUserPermissionDo
	Join(table schema.Tabler, on ...field.Expr) IRegistryUserPermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryUserPermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRegistryUserPermissionDo
	Group(cols ...field.Expr) IRegistryUserPermissionDo
	Having(conds ...gen.Condition) IRegistryUserPermissionDo
	Limit(limit int) IRegistryUserPermissionDo
	Offset(offset int) IRegistryUserPermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryUserPermissionDo
	Unscoped() IRegistryUserPermissionDo
	Create(values ...*entity.RegistryUserPermission) error
	CreateInBatches(values []*entity.RegistryUserPermission, batchSize int) error
	Save(values ...*entity.RegistryUserPermission) error
	First() (*entity.RegistryUserPermission, error)
	Take() (*entity.RegistryUserPermission, error)
	Last() (*entity.RegistryUserPermission, error)
	Find() ([]*entity.RegistryUserPermission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryUserPermission, err error)
	FindInBatches(result *[]*entity.RegistryUserPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.RegistryUserPermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRegistryUserPermissionDo
	Assign(attrs ...field.AssignExpr) IRegistryUserPermissionDo
	Joins(fields ...field.RelationField) IRegistryUserPermissionDo
	Preload(fields ...field.RelationField) IRegistryUserPermissionDo
	FirstOrInit() (*entity.RegistryUserPermission, error)
	FirstOrCreate() (*entity.RegistryUserPermission, error)
	FindByPage(offset int, limit int) (result []*entity.RegistryUserPermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRegistryUserPermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r registryUserPermissionDo) Debug() IRegistryUserPermissionDo {
	return r.withDO(r.DO.Debug())
}

func (r registryUserPermissionDo) WithContext(ctx context.Context) IRegistryUserPermissionDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r registryUserPermissionDo) ReadDB() IRegistryUserPermissionDo {
	return r.Clauses(dbresolver.Read)
}

func (r registryUserPermissionDo) WriteDB() IRegistryUserPermissionDo {
	return r.Clauses(dbresolver.Write)
}

func (r registryUserPermissionDo) Session(config *gorm.Session) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Session(config))
}

func (r registryUserPermissionDo) Clauses(conds ...clause.Expression) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r registryUserPermissionDo) Returning(value interface{}, columns ...string) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r registryUserPermissionDo) Not(conds ...gen.Condition) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r registryUserPermissionDo) Or(conds ...gen.Condition) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r registryUserPermissionDo) Select(conds ...field.Expr) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r registryUserPermissionDo) Where(conds ...gen.Condition) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r registryUserPermissionDo) Order(conds ...field.Expr) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r registryUserPermissionDo) Distinct(cols ...field.Expr) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r registryUserPermissionDo) Omit(cols ...field.Expr) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r registryUserPermissionDo) Join(table schema.Tabler, on ...field.Expr) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r registryUserPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryUserPermissionDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r registryUserPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) IRegistryUserPermissionDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r registryUserPermissionDo) Group(cols ...field.Expr) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r registryUserPermissionDo) Having(conds ...gen.Condition) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r registryUserPermissionDo) Limit(limit int) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r registryUserPermissionDo) Offset(offset int) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r registryUserPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r registryUserPermissionDo) Unscoped() IRegistryUserPermissionDo {
	return r.withDO(r.DO.Unscoped())
}

func (r registryUserPermissionDo) Create(values ...*entity.RegistryUserPermission) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r registryUserPermissionDo) CreateInBatches(values []*entity.RegistryUserPermission, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r registryUserPermissionDo) Save(values ...*entity.RegistryUserPermission) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r registryUserPermissionDo) First() (*entity.RegistryUserPermission, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryUserPermission), nil
	}
}

func (r registryUserPermissionDo) Take() (*entity.RegistryUserPermission, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryUserPermission), nil
	}
}

func (r registryUserPermissionDo) Last() (*entity.RegistryUserPermission, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryUserPermission), nil
	}
}

func (r registryUserPermissionDo) Find() ([]*entity.RegistryUserPermission, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RegistryUserPermission), err
}

func (r registryUserPermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryUserPermission, err error) {
	buf := make([]*entity.RegistryUserPermission, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r registryUserPermissionDo) FindInBatches(result *[]*entity.RegistryUserPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r registryUserPermissionDo) Attrs(attrs ...field.AssignExpr) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r registryUserPermissionDo) Assign(attrs ...field.AssignExpr) IRegistryUserPermissionDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r registryUserPermissionDo) Joins(fields ...field.RelationField) IRegistryUserPermissionDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r registryUserPermissionDo) Preload(fields ...field.RelationField) IRegistryUserPermissionDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r registryUserPermissionDo) FirstOrInit() (*entity.RegistryUserPermission, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryUserPermission), nil
	}
}

func (r registryUserPermissionDo) FirstOrCreate() (*entity.RegistryUserPermission, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryUserPermission), nil
	}
}

func (r registryUserPermissionDo) FindByPage(offset int, limit int) (result []*entity.RegistryUserPermission, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r registryUserPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r registryUserPermissionDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r registryUserPermissionDo) Delete(models ...*entity.RegistryUserPermission) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *registryUserPermissionDo) withDO(do gen.Dao) *registryUserPermissionDo {
	r.DO = *do.(*gen.DO)
	return r
}
