// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-zpk/common/entity"
)

func newRegistryRepositoryDeployRule(db *gorm.DB, opts ...gen.DOOption) registryRepositoryDeployRule {
	_registryRepositoryDeployRule := registryRepositoryDeployRule{}

	_registryRepositoryDeployRule.registryRepositoryDeployRuleDo.UseDB(db, opts...)
	_registryRepositoryDeployRule.registryRepositoryDeployRuleDo.UseModel(&entity.RegistryRepositoryDeployRule{})

	tableName := _registryRepositoryDeployRule.registryRepositoryDeployRuleDo.TableName()
	_registryRepositoryDeployRule.ALL = field.NewAsterisk(tableName)
	_registryRepositoryDeployRule.ID = field.NewInt32(tableName, "id")
	_registryRepositoryDeployRule.RepositoryID = field.NewInt32(tableName, "repository_id")
	_registryRepositoryDeployRule.DeployType = field.NewInt32(tableName, "deploy_type")
	_registryRepositoryDeployRule.MatchType = field.NewInt32(tableName, "match_type")
	_registryRepositoryDeployRule.TagName = field.NewString(tableName, "tag_name")
	_registryRepositoryDeployRule.K8sConfig = field.NewString(tableName, "k8s_config")
	_registryRepositoryDeployRule.K8sNamespace = field.NewString(tableName, "k8s_namespace")
	_registryRepositoryDeployRule.K8sControllerType = field.NewString(tableName, "k8s_controller_type")
	_registryRepositoryDeployRule.K8sAppName = field.NewString(tableName, "k8s_app_name")
	_registryRepositoryDeployRule.K8sContainerName = field.NewString(tableName, "k8s_container_name")
	_registryRepositoryDeployRule.CreatedAt = field.NewTime(tableName, "created_at")
	_registryRepositoryDeployRule.LatestTriggerAt = field.NewTime(tableName, "latest_trigger_at")

	_registryRepositoryDeployRule.fillFieldMap()

	return _registryRepositoryDeployRule
}

type registryRepositoryDeployRule struct {
	registryRepositoryDeployRuleDo

	ALL               field.Asterisk
	ID                field.Int32
	RepositoryID      field.Int32
	DeployType        field.Int32
	MatchType         field.Int32
	TagName           field.String
	K8sConfig         field.String
	K8sNamespace      field.String
	K8sControllerType field.String
	K8sAppName        field.String
	K8sContainerName  field.String
	CreatedAt         field.Time
	LatestTriggerAt   field.Time

	fieldMap map[string]field.Expr
}

func (r registryRepositoryDeployRule) Table(newTableName string) *registryRepositoryDeployRule {
	r.registryRepositoryDeployRuleDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r registryRepositoryDeployRule) As(alias string) *registryRepositoryDeployRule {
	r.registryRepositoryDeployRuleDo.DO = *(r.registryRepositoryDeployRuleDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *registryRepositoryDeployRule) updateTableName(table string) *registryRepositoryDeployRule {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.RepositoryID = field.NewInt32(table, "repository_id")
	r.DeployType = field.NewInt32(table, "deploy_type")
	r.MatchType = field.NewInt32(table, "match_type")
	r.TagName = field.NewString(table, "tag_name")
	r.K8sConfig = field.NewString(table, "k8s_config")
	r.K8sNamespace = field.NewString(table, "k8s_namespace")
	r.K8sControllerType = field.NewString(table, "k8s_controller_type")
	r.K8sAppName = field.NewString(table, "k8s_app_name")
	r.K8sContainerName = field.NewString(table, "k8s_container_name")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.LatestTriggerAt = field.NewTime(table, "latest_trigger_at")

	r.fillFieldMap()

	return r
}

func (r *registryRepositoryDeployRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *registryRepositoryDeployRule) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 12)
	r.fieldMap["id"] = r.ID
	r.fieldMap["repository_id"] = r.RepositoryID
	r.fieldMap["deploy_type"] = r.DeployType
	r.fieldMap["match_type"] = r.MatchType
	r.fieldMap["tag_name"] = r.TagName
	r.fieldMap["k8s_config"] = r.K8sConfig
	r.fieldMap["k8s_namespace"] = r.K8sNamespace
	r.fieldMap["k8s_controller_type"] = r.K8sControllerType
	r.fieldMap["k8s_app_name"] = r.K8sAppName
	r.fieldMap["k8s_container_name"] = r.K8sContainerName
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["latest_trigger_at"] = r.LatestTriggerAt
}

func (r registryRepositoryDeployRule) clone(db *gorm.DB) registryRepositoryDeployRule {
	r.registryRepositoryDeployRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r registryRepositoryDeployRule) replaceDB(db *gorm.DB) registryRepositoryDeployRule {
	r.registryRepositoryDeployRuleDo.ReplaceDB(db)
	return r
}

type registryRepositoryDeployRuleDo struct{ gen.DO }

type IRegistryRepositoryDeployRuleDo interface {
	gen.SubQuery
	Debug() IRegistryRepositoryDeployRuleDo
	WithContext(ctx context.Context) IRegistryRepositoryDeployRuleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRegistryRepositoryDeployRuleDo
	WriteDB() IRegistryRepositoryDeployRuleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRegistryRepositoryDeployRuleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRegistryRepositoryDeployRuleDo
	Not(conds ...gen.Condition) IRegistryRepositoryDeployRuleDo
	Or(conds ...gen.Condition) IRegistryRepositoryDeployRuleDo
	Select(conds ...field.Expr) IRegistryRepositoryDeployRuleDo
	Where(conds ...gen.Condition) IRegistryRepositoryDeployRuleDo
	Order(conds ...field.Expr) IRegistryRepositoryDeployRuleDo
	Distinct(cols ...field.Expr) IRegistryRepositoryDeployRuleDo
	Omit(cols ...field.Expr) IRegistryRepositoryDeployRuleDo
	Join(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleDo
	Group(cols ...field.Expr) IRegistryRepositoryDeployRuleDo
	Having(conds ...gen.Condition) IRegistryRepositoryDeployRuleDo
	Limit(limit int) IRegistryRepositoryDeployRuleDo
	Offset(offset int) IRegistryRepositoryDeployRuleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryRepositoryDeployRuleDo
	Unscoped() IRegistryRepositoryDeployRuleDo
	Create(values ...*entity.RegistryRepositoryDeployRule) error
	CreateInBatches(values []*entity.RegistryRepositoryDeployRule, batchSize int) error
	Save(values ...*entity.RegistryRepositoryDeployRule) error
	First() (*entity.RegistryRepositoryDeployRule, error)
	Take() (*entity.RegistryRepositoryDeployRule, error)
	Last() (*entity.RegistryRepositoryDeployRule, error)
	Find() ([]*entity.RegistryRepositoryDeployRule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryRepositoryDeployRule, err error)
	FindInBatches(result *[]*entity.RegistryRepositoryDeployRule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.RegistryRepositoryDeployRule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRegistryRepositoryDeployRuleDo
	Assign(attrs ...field.AssignExpr) IRegistryRepositoryDeployRuleDo
	Joins(fields ...field.RelationField) IRegistryRepositoryDeployRuleDo
	Preload(fields ...field.RelationField) IRegistryRepositoryDeployRuleDo
	FirstOrInit() (*entity.RegistryRepositoryDeployRule, error)
	FirstOrCreate() (*entity.RegistryRepositoryDeployRule, error)
	FindByPage(offset int, limit int) (result []*entity.RegistryRepositoryDeployRule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRegistryRepositoryDeployRuleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r registryRepositoryDeployRuleDo) Debug() IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Debug())
}

func (r registryRepositoryDeployRuleDo) WithContext(ctx context.Context) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r registryRepositoryDeployRuleDo) ReadDB() IRegistryRepositoryDeployRuleDo {
	return r.Clauses(dbresolver.Read)
}

func (r registryRepositoryDeployRuleDo) WriteDB() IRegistryRepositoryDeployRuleDo {
	return r.Clauses(dbresolver.Write)
}

func (r registryRepositoryDeployRuleDo) Session(config *gorm.Session) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Session(config))
}

func (r registryRepositoryDeployRuleDo) Clauses(conds ...clause.Expression) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r registryRepositoryDeployRuleDo) Returning(value interface{}, columns ...string) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r registryRepositoryDeployRuleDo) Not(conds ...gen.Condition) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r registryRepositoryDeployRuleDo) Or(conds ...gen.Condition) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r registryRepositoryDeployRuleDo) Select(conds ...field.Expr) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r registryRepositoryDeployRuleDo) Where(conds ...gen.Condition) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r registryRepositoryDeployRuleDo) Order(conds ...field.Expr) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r registryRepositoryDeployRuleDo) Distinct(cols ...field.Expr) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r registryRepositoryDeployRuleDo) Omit(cols ...field.Expr) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r registryRepositoryDeployRuleDo) Join(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r registryRepositoryDeployRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r registryRepositoryDeployRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r registryRepositoryDeployRuleDo) Group(cols ...field.Expr) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r registryRepositoryDeployRuleDo) Having(conds ...gen.Condition) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r registryRepositoryDeployRuleDo) Limit(limit int) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r registryRepositoryDeployRuleDo) Offset(offset int) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r registryRepositoryDeployRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r registryRepositoryDeployRuleDo) Unscoped() IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Unscoped())
}

func (r registryRepositoryDeployRuleDo) Create(values ...*entity.RegistryRepositoryDeployRule) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r registryRepositoryDeployRuleDo) CreateInBatches(values []*entity.RegistryRepositoryDeployRule, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r registryRepositoryDeployRuleDo) Save(values ...*entity.RegistryRepositoryDeployRule) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r registryRepositoryDeployRuleDo) First() (*entity.RegistryRepositoryDeployRule, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryDeployRule), nil
	}
}

func (r registryRepositoryDeployRuleDo) Take() (*entity.RegistryRepositoryDeployRule, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryDeployRule), nil
	}
}

func (r registryRepositoryDeployRuleDo) Last() (*entity.RegistryRepositoryDeployRule, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryDeployRule), nil
	}
}

func (r registryRepositoryDeployRuleDo) Find() ([]*entity.RegistryRepositoryDeployRule, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RegistryRepositoryDeployRule), err
}

func (r registryRepositoryDeployRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryRepositoryDeployRule, err error) {
	buf := make([]*entity.RegistryRepositoryDeployRule, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r registryRepositoryDeployRuleDo) FindInBatches(result *[]*entity.RegistryRepositoryDeployRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r registryRepositoryDeployRuleDo) Attrs(attrs ...field.AssignExpr) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r registryRepositoryDeployRuleDo) Assign(attrs ...field.AssignExpr) IRegistryRepositoryDeployRuleDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r registryRepositoryDeployRuleDo) Joins(fields ...field.RelationField) IRegistryRepositoryDeployRuleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r registryRepositoryDeployRuleDo) Preload(fields ...field.RelationField) IRegistryRepositoryDeployRuleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r registryRepositoryDeployRuleDo) FirstOrInit() (*entity.RegistryRepositoryDeployRule, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryDeployRule), nil
	}
}

func (r registryRepositoryDeployRuleDo) FirstOrCreate() (*entity.RegistryRepositoryDeployRule, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryDeployRule), nil
	}
}

func (r registryRepositoryDeployRuleDo) FindByPage(offset int, limit int) (result []*entity.RegistryRepositoryDeployRule, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r registryRepositoryDeployRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r registryRepositoryDeployRuleDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r registryRepositoryDeployRuleDo) Delete(models ...*entity.RegistryRepositoryDeployRule) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *registryRepositoryDeployRuleDo) withDO(do gen.Dao) *registryRepositoryDeployRuleDo {
	r.DO = *do.(*gen.DO)
	return r
}
