// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-zpk/common/entity"
)

func newFormulaSettingValue(db *gorm.DB, opts ...gen.DOOption) formulaSettingValue {
	_formulaSettingValue := formulaSettingValue{}

	_formulaSettingValue.formulaSettingValueDo.UseDB(db, opts...)
	_formulaSettingValue.formulaSettingValueDo.UseModel(&entity.FormulaSettingValue{})

	tableName := _formulaSettingValue.formulaSettingValueDo.TableName()
	_formulaSettingValue.ALL = field.NewAsterisk(tableName)
	_formulaSettingValue.ID = field.NewInt32(tableName, "id")
	_formulaSettingValue.Value = field.NewString(tableName, "value")

	_formulaSettingValue.fillFieldMap()

	return _formulaSettingValue
}

type formulaSettingValue struct {
	formulaSettingValueDo

	ALL   field.Asterisk
	ID    field.Int32
	Value field.String

	fieldMap map[string]field.Expr
}

func (f formulaSettingValue) Table(newTableName string) *formulaSettingValue {
	f.formulaSettingValueDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f formulaSettingValue) As(alias string) *formulaSettingValue {
	f.formulaSettingValueDo.DO = *(f.formulaSettingValueDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *formulaSettingValue) updateTableName(table string) *formulaSettingValue {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt32(table, "id")
	f.Value = field.NewString(table, "value")

	f.fillFieldMap()

	return f
}

func (f *formulaSettingValue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *formulaSettingValue) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 2)
	f.fieldMap["id"] = f.ID
	f.fieldMap["value"] = f.Value
}

func (f formulaSettingValue) clone(db *gorm.DB) formulaSettingValue {
	f.formulaSettingValueDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f formulaSettingValue) replaceDB(db *gorm.DB) formulaSettingValue {
	f.formulaSettingValueDo.ReplaceDB(db)
	return f
}

type formulaSettingValueDo struct{ gen.DO }

type IFormulaSettingValueDo interface {
	gen.SubQuery
	Debug() IFormulaSettingValueDo
	WithContext(ctx context.Context) IFormulaSettingValueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFormulaSettingValueDo
	WriteDB() IFormulaSettingValueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFormulaSettingValueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFormulaSettingValueDo
	Not(conds ...gen.Condition) IFormulaSettingValueDo
	Or(conds ...gen.Condition) IFormulaSettingValueDo
	Select(conds ...field.Expr) IFormulaSettingValueDo
	Where(conds ...gen.Condition) IFormulaSettingValueDo
	Order(conds ...field.Expr) IFormulaSettingValueDo
	Distinct(cols ...field.Expr) IFormulaSettingValueDo
	Omit(cols ...field.Expr) IFormulaSettingValueDo
	Join(table schema.Tabler, on ...field.Expr) IFormulaSettingValueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFormulaSettingValueDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFormulaSettingValueDo
	Group(cols ...field.Expr) IFormulaSettingValueDo
	Having(conds ...gen.Condition) IFormulaSettingValueDo
	Limit(limit int) IFormulaSettingValueDo
	Offset(offset int) IFormulaSettingValueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFormulaSettingValueDo
	Unscoped() IFormulaSettingValueDo
	Create(values ...*entity.FormulaSettingValue) error
	CreateInBatches(values []*entity.FormulaSettingValue, batchSize int) error
	Save(values ...*entity.FormulaSettingValue) error
	First() (*entity.FormulaSettingValue, error)
	Take() (*entity.FormulaSettingValue, error)
	Last() (*entity.FormulaSettingValue, error)
	Find() ([]*entity.FormulaSettingValue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.FormulaSettingValue, err error)
	FindInBatches(result *[]*entity.FormulaSettingValue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.FormulaSettingValue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFormulaSettingValueDo
	Assign(attrs ...field.AssignExpr) IFormulaSettingValueDo
	Joins(fields ...field.RelationField) IFormulaSettingValueDo
	Preload(fields ...field.RelationField) IFormulaSettingValueDo
	FirstOrInit() (*entity.FormulaSettingValue, error)
	FirstOrCreate() (*entity.FormulaSettingValue, error)
	FindByPage(offset int, limit int) (result []*entity.FormulaSettingValue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFormulaSettingValueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f formulaSettingValueDo) Debug() IFormulaSettingValueDo {
	return f.withDO(f.DO.Debug())
}

func (f formulaSettingValueDo) WithContext(ctx context.Context) IFormulaSettingValueDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f formulaSettingValueDo) ReadDB() IFormulaSettingValueDo {
	return f.Clauses(dbresolver.Read)
}

func (f formulaSettingValueDo) WriteDB() IFormulaSettingValueDo {
	return f.Clauses(dbresolver.Write)
}

func (f formulaSettingValueDo) Session(config *gorm.Session) IFormulaSettingValueDo {
	return f.withDO(f.DO.Session(config))
}

func (f formulaSettingValueDo) Clauses(conds ...clause.Expression) IFormulaSettingValueDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f formulaSettingValueDo) Returning(value interface{}, columns ...string) IFormulaSettingValueDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f formulaSettingValueDo) Not(conds ...gen.Condition) IFormulaSettingValueDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f formulaSettingValueDo) Or(conds ...gen.Condition) IFormulaSettingValueDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f formulaSettingValueDo) Select(conds ...field.Expr) IFormulaSettingValueDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f formulaSettingValueDo) Where(conds ...gen.Condition) IFormulaSettingValueDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f formulaSettingValueDo) Order(conds ...field.Expr) IFormulaSettingValueDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f formulaSettingValueDo) Distinct(cols ...field.Expr) IFormulaSettingValueDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f formulaSettingValueDo) Omit(cols ...field.Expr) IFormulaSettingValueDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f formulaSettingValueDo) Join(table schema.Tabler, on ...field.Expr) IFormulaSettingValueDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f formulaSettingValueDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFormulaSettingValueDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f formulaSettingValueDo) RightJoin(table schema.Tabler, on ...field.Expr) IFormulaSettingValueDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f formulaSettingValueDo) Group(cols ...field.Expr) IFormulaSettingValueDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f formulaSettingValueDo) Having(conds ...gen.Condition) IFormulaSettingValueDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f formulaSettingValueDo) Limit(limit int) IFormulaSettingValueDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f formulaSettingValueDo) Offset(offset int) IFormulaSettingValueDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f formulaSettingValueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFormulaSettingValueDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f formulaSettingValueDo) Unscoped() IFormulaSettingValueDo {
	return f.withDO(f.DO.Unscoped())
}

func (f formulaSettingValueDo) Create(values ...*entity.FormulaSettingValue) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f formulaSettingValueDo) CreateInBatches(values []*entity.FormulaSettingValue, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f formulaSettingValueDo) Save(values ...*entity.FormulaSettingValue) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f formulaSettingValueDo) First() (*entity.FormulaSettingValue, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FormulaSettingValue), nil
	}
}

func (f formulaSettingValueDo) Take() (*entity.FormulaSettingValue, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FormulaSettingValue), nil
	}
}

func (f formulaSettingValueDo) Last() (*entity.FormulaSettingValue, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FormulaSettingValue), nil
	}
}

func (f formulaSettingValueDo) Find() ([]*entity.FormulaSettingValue, error) {
	result, err := f.DO.Find()
	return result.([]*entity.FormulaSettingValue), err
}

func (f formulaSettingValueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.FormulaSettingValue, err error) {
	buf := make([]*entity.FormulaSettingValue, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f formulaSettingValueDo) FindInBatches(result *[]*entity.FormulaSettingValue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f formulaSettingValueDo) Attrs(attrs ...field.AssignExpr) IFormulaSettingValueDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f formulaSettingValueDo) Assign(attrs ...field.AssignExpr) IFormulaSettingValueDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f formulaSettingValueDo) Joins(fields ...field.RelationField) IFormulaSettingValueDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f formulaSettingValueDo) Preload(fields ...field.RelationField) IFormulaSettingValueDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f formulaSettingValueDo) FirstOrInit() (*entity.FormulaSettingValue, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FormulaSettingValue), nil
	}
}

func (f formulaSettingValueDo) FirstOrCreate() (*entity.FormulaSettingValue, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FormulaSettingValue), nil
	}
}

func (f formulaSettingValueDo) FindByPage(offset int, limit int) (result []*entity.FormulaSettingValue, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f formulaSettingValueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f formulaSettingValueDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f formulaSettingValueDo) Delete(models ...*entity.FormulaSettingValue) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *formulaSettingValueDo) withDO(do gen.Dao) *formulaSettingValueDo {
	f.DO = *do.(*gen.DO)
	return f
}
