// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-zpk/common/entity"
)

func newFormulaSetting(db *gorm.DB, opts ...gen.DOOption) formulaSetting {
	_formulaSetting := formulaSetting{}

	_formulaSetting.formulaSettingDo.UseDB(db, opts...)
	_formulaSetting.formulaSettingDo.UseModel(&entity.FormulaSetting{})

	tableName := _formulaSetting.formulaSettingDo.TableName()
	_formulaSetting.ALL = field.NewAsterisk(tableName)
	_formulaSetting.ID = field.NewInt32(tableName, "id")
	_formulaSetting.FormulaID = field.NewInt32(tableName, "formula_id")
	_formulaSetting.VersionID = field.NewInt32(tableName, "version_id")
	_formulaSetting.SettingValueID = field.NewInt32(tableName, "setting_value_id")
	_formulaSetting.Type = field.NewInt32(tableName, "type")
	_formulaSetting.Name = field.NewString(tableName, "name")
	_formulaSetting.FormulaSettingValue = formulaSettingHasOneFormulaSettingValue{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("FormulaSettingValue", "entity.FormulaSettingValue"),
	}

	_formulaSetting.fillFieldMap()

	return _formulaSetting
}

type formulaSetting struct {
	formulaSettingDo

	ALL                 field.Asterisk
	ID                  field.Int32
	FormulaID           field.Int32
	VersionID           field.Int32
	SettingValueID      field.Int32
	Type                field.Int32 // 1为文件，2为配置
	Name                field.String
	FormulaSettingValue formulaSettingHasOneFormulaSettingValue

	fieldMap map[string]field.Expr
}

func (f formulaSetting) Table(newTableName string) *formulaSetting {
	f.formulaSettingDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f formulaSetting) As(alias string) *formulaSetting {
	f.formulaSettingDo.DO = *(f.formulaSettingDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *formulaSetting) updateTableName(table string) *formulaSetting {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt32(table, "id")
	f.FormulaID = field.NewInt32(table, "formula_id")
	f.VersionID = field.NewInt32(table, "version_id")
	f.SettingValueID = field.NewInt32(table, "setting_value_id")
	f.Type = field.NewInt32(table, "type")
	f.Name = field.NewString(table, "name")

	f.fillFieldMap()

	return f
}

func (f *formulaSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *formulaSetting) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 7)
	f.fieldMap["id"] = f.ID
	f.fieldMap["formula_id"] = f.FormulaID
	f.fieldMap["version_id"] = f.VersionID
	f.fieldMap["setting_value_id"] = f.SettingValueID
	f.fieldMap["type"] = f.Type
	f.fieldMap["name"] = f.Name

}

func (f formulaSetting) clone(db *gorm.DB) formulaSetting {
	f.formulaSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f formulaSetting) replaceDB(db *gorm.DB) formulaSetting {
	f.formulaSettingDo.ReplaceDB(db)
	return f
}

type formulaSettingHasOneFormulaSettingValue struct {
	db *gorm.DB

	field.RelationField
}

func (a formulaSettingHasOneFormulaSettingValue) Where(conds ...field.Expr) *formulaSettingHasOneFormulaSettingValue {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a formulaSettingHasOneFormulaSettingValue) WithContext(ctx context.Context) *formulaSettingHasOneFormulaSettingValue {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a formulaSettingHasOneFormulaSettingValue) Session(session *gorm.Session) *formulaSettingHasOneFormulaSettingValue {
	a.db = a.db.Session(session)
	return &a
}

func (a formulaSettingHasOneFormulaSettingValue) Model(m *entity.FormulaSetting) *formulaSettingHasOneFormulaSettingValueTx {
	return &formulaSettingHasOneFormulaSettingValueTx{a.db.Model(m).Association(a.Name())}
}

type formulaSettingHasOneFormulaSettingValueTx struct{ tx *gorm.Association }

func (a formulaSettingHasOneFormulaSettingValueTx) Find() (result *entity.FormulaSettingValue, err error) {
	return result, a.tx.Find(&result)
}

func (a formulaSettingHasOneFormulaSettingValueTx) Append(values ...*entity.FormulaSettingValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a formulaSettingHasOneFormulaSettingValueTx) Replace(values ...*entity.FormulaSettingValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a formulaSettingHasOneFormulaSettingValueTx) Delete(values ...*entity.FormulaSettingValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a formulaSettingHasOneFormulaSettingValueTx) Clear() error {
	return a.tx.Clear()
}

func (a formulaSettingHasOneFormulaSettingValueTx) Count() int64 {
	return a.tx.Count()
}

type formulaSettingDo struct{ gen.DO }

type IFormulaSettingDo interface {
	gen.SubQuery
	Debug() IFormulaSettingDo
	WithContext(ctx context.Context) IFormulaSettingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFormulaSettingDo
	WriteDB() IFormulaSettingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFormulaSettingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFormulaSettingDo
	Not(conds ...gen.Condition) IFormulaSettingDo
	Or(conds ...gen.Condition) IFormulaSettingDo
	Select(conds ...field.Expr) IFormulaSettingDo
	Where(conds ...gen.Condition) IFormulaSettingDo
	Order(conds ...field.Expr) IFormulaSettingDo
	Distinct(cols ...field.Expr) IFormulaSettingDo
	Omit(cols ...field.Expr) IFormulaSettingDo
	Join(table schema.Tabler, on ...field.Expr) IFormulaSettingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFormulaSettingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFormulaSettingDo
	Group(cols ...field.Expr) IFormulaSettingDo
	Having(conds ...gen.Condition) IFormulaSettingDo
	Limit(limit int) IFormulaSettingDo
	Offset(offset int) IFormulaSettingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFormulaSettingDo
	Unscoped() IFormulaSettingDo
	Create(values ...*entity.FormulaSetting) error
	CreateInBatches(values []*entity.FormulaSetting, batchSize int) error
	Save(values ...*entity.FormulaSetting) error
	First() (*entity.FormulaSetting, error)
	Take() (*entity.FormulaSetting, error)
	Last() (*entity.FormulaSetting, error)
	Find() ([]*entity.FormulaSetting, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.FormulaSetting, err error)
	FindInBatches(result *[]*entity.FormulaSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.FormulaSetting) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFormulaSettingDo
	Assign(attrs ...field.AssignExpr) IFormulaSettingDo
	Joins(fields ...field.RelationField) IFormulaSettingDo
	Preload(fields ...field.RelationField) IFormulaSettingDo
	FirstOrInit() (*entity.FormulaSetting, error)
	FirstOrCreate() (*entity.FormulaSetting, error)
	FindByPage(offset int, limit int) (result []*entity.FormulaSetting, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFormulaSettingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f formulaSettingDo) Debug() IFormulaSettingDo {
	return f.withDO(f.DO.Debug())
}

func (f formulaSettingDo) WithContext(ctx context.Context) IFormulaSettingDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f formulaSettingDo) ReadDB() IFormulaSettingDo {
	return f.Clauses(dbresolver.Read)
}

func (f formulaSettingDo) WriteDB() IFormulaSettingDo {
	return f.Clauses(dbresolver.Write)
}

func (f formulaSettingDo) Session(config *gorm.Session) IFormulaSettingDo {
	return f.withDO(f.DO.Session(config))
}

func (f formulaSettingDo) Clauses(conds ...clause.Expression) IFormulaSettingDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f formulaSettingDo) Returning(value interface{}, columns ...string) IFormulaSettingDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f formulaSettingDo) Not(conds ...gen.Condition) IFormulaSettingDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f formulaSettingDo) Or(conds ...gen.Condition) IFormulaSettingDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f formulaSettingDo) Select(conds ...field.Expr) IFormulaSettingDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f formulaSettingDo) Where(conds ...gen.Condition) IFormulaSettingDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f formulaSettingDo) Order(conds ...field.Expr) IFormulaSettingDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f formulaSettingDo) Distinct(cols ...field.Expr) IFormulaSettingDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f formulaSettingDo) Omit(cols ...field.Expr) IFormulaSettingDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f formulaSettingDo) Join(table schema.Tabler, on ...field.Expr) IFormulaSettingDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f formulaSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFormulaSettingDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f formulaSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) IFormulaSettingDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f formulaSettingDo) Group(cols ...field.Expr) IFormulaSettingDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f formulaSettingDo) Having(conds ...gen.Condition) IFormulaSettingDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f formulaSettingDo) Limit(limit int) IFormulaSettingDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f formulaSettingDo) Offset(offset int) IFormulaSettingDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f formulaSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFormulaSettingDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f formulaSettingDo) Unscoped() IFormulaSettingDo {
	return f.withDO(f.DO.Unscoped())
}

func (f formulaSettingDo) Create(values ...*entity.FormulaSetting) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f formulaSettingDo) CreateInBatches(values []*entity.FormulaSetting, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f formulaSettingDo) Save(values ...*entity.FormulaSetting) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f formulaSettingDo) First() (*entity.FormulaSetting, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FormulaSetting), nil
	}
}

func (f formulaSettingDo) Take() (*entity.FormulaSetting, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FormulaSetting), nil
	}
}

func (f formulaSettingDo) Last() (*entity.FormulaSetting, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FormulaSetting), nil
	}
}

func (f formulaSettingDo) Find() ([]*entity.FormulaSetting, error) {
	result, err := f.DO.Find()
	return result.([]*entity.FormulaSetting), err
}

func (f formulaSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.FormulaSetting, err error) {
	buf := make([]*entity.FormulaSetting, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f formulaSettingDo) FindInBatches(result *[]*entity.FormulaSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f formulaSettingDo) Attrs(attrs ...field.AssignExpr) IFormulaSettingDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f formulaSettingDo) Assign(attrs ...field.AssignExpr) IFormulaSettingDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f formulaSettingDo) Joins(fields ...field.RelationField) IFormulaSettingDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f formulaSettingDo) Preload(fields ...field.RelationField) IFormulaSettingDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f formulaSettingDo) FirstOrInit() (*entity.FormulaSetting, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FormulaSetting), nil
	}
}

func (f formulaSettingDo) FirstOrCreate() (*entity.FormulaSetting, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FormulaSetting), nil
	}
}

func (f formulaSettingDo) FindByPage(offset int, limit int) (result []*entity.FormulaSetting, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f formulaSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f formulaSettingDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f formulaSettingDo) Delete(models ...*entity.FormulaSetting) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *formulaSettingDo) withDO(do gen.Dao) *formulaSettingDo {
	f.DO = *do.(*gen.DO)
	return f
}
