// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-zpk/common/entity"
)

func newRegistryRepositoryDeployRuleMatchLog(db *gorm.DB, opts ...gen.DOOption) registryRepositoryDeployRuleMatchLog {
	_registryRepositoryDeployRuleMatchLog := registryRepositoryDeployRuleMatchLog{}

	_registryRepositoryDeployRuleMatchLog.registryRepositoryDeployRuleMatchLogDo.UseDB(db, opts...)
	_registryRepositoryDeployRuleMatchLog.registryRepositoryDeployRuleMatchLogDo.UseModel(&entity.RegistryRepositoryDeployRuleMatchLog{})

	tableName := _registryRepositoryDeployRuleMatchLog.registryRepositoryDeployRuleMatchLogDo.TableName()
	_registryRepositoryDeployRuleMatchLog.ALL = field.NewAsterisk(tableName)
	_registryRepositoryDeployRuleMatchLog.ID = field.NewInt32(tableName, "id")
	_registryRepositoryDeployRuleMatchLog.RuleID = field.NewInt32(tableName, "rule_id")
	_registryRepositoryDeployRuleMatchLog.ImageName = field.NewString(tableName, "image_name")
	_registryRepositoryDeployRuleMatchLog.K8sLog = field.NewString(tableName, "k8s_log")
	_registryRepositoryDeployRuleMatchLog.CreatedAt = field.NewTime(tableName, "created_at")

	_registryRepositoryDeployRuleMatchLog.fillFieldMap()

	return _registryRepositoryDeployRuleMatchLog
}

type registryRepositoryDeployRuleMatchLog struct {
	registryRepositoryDeployRuleMatchLogDo

	ALL       field.Asterisk
	ID        field.Int32
	RuleID    field.Int32
	ImageName field.String
	K8sLog    field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r registryRepositoryDeployRuleMatchLog) Table(newTableName string) *registryRepositoryDeployRuleMatchLog {
	r.registryRepositoryDeployRuleMatchLogDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r registryRepositoryDeployRuleMatchLog) As(alias string) *registryRepositoryDeployRuleMatchLog {
	r.registryRepositoryDeployRuleMatchLogDo.DO = *(r.registryRepositoryDeployRuleMatchLogDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *registryRepositoryDeployRuleMatchLog) updateTableName(table string) *registryRepositoryDeployRuleMatchLog {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.RuleID = field.NewInt32(table, "rule_id")
	r.ImageName = field.NewString(table, "image_name")
	r.K8sLog = field.NewString(table, "k8s_log")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *registryRepositoryDeployRuleMatchLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *registryRepositoryDeployRuleMatchLog) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 5)
	r.fieldMap["id"] = r.ID
	r.fieldMap["rule_id"] = r.RuleID
	r.fieldMap["image_name"] = r.ImageName
	r.fieldMap["k8s_log"] = r.K8sLog
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r registryRepositoryDeployRuleMatchLog) clone(db *gorm.DB) registryRepositoryDeployRuleMatchLog {
	r.registryRepositoryDeployRuleMatchLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r registryRepositoryDeployRuleMatchLog) replaceDB(db *gorm.DB) registryRepositoryDeployRuleMatchLog {
	r.registryRepositoryDeployRuleMatchLogDo.ReplaceDB(db)
	return r
}

type registryRepositoryDeployRuleMatchLogDo struct{ gen.DO }

type IRegistryRepositoryDeployRuleMatchLogDo interface {
	gen.SubQuery
	Debug() IRegistryRepositoryDeployRuleMatchLogDo
	WithContext(ctx context.Context) IRegistryRepositoryDeployRuleMatchLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRegistryRepositoryDeployRuleMatchLogDo
	WriteDB() IRegistryRepositoryDeployRuleMatchLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRegistryRepositoryDeployRuleMatchLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRegistryRepositoryDeployRuleMatchLogDo
	Not(conds ...gen.Condition) IRegistryRepositoryDeployRuleMatchLogDo
	Or(conds ...gen.Condition) IRegistryRepositoryDeployRuleMatchLogDo
	Select(conds ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo
	Where(conds ...gen.Condition) IRegistryRepositoryDeployRuleMatchLogDo
	Order(conds ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo
	Distinct(cols ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo
	Omit(cols ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo
	Join(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo
	Group(cols ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo
	Having(conds ...gen.Condition) IRegistryRepositoryDeployRuleMatchLogDo
	Limit(limit int) IRegistryRepositoryDeployRuleMatchLogDo
	Offset(offset int) IRegistryRepositoryDeployRuleMatchLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryRepositoryDeployRuleMatchLogDo
	Unscoped() IRegistryRepositoryDeployRuleMatchLogDo
	Create(values ...*entity.RegistryRepositoryDeployRuleMatchLog) error
	CreateInBatches(values []*entity.RegistryRepositoryDeployRuleMatchLog, batchSize int) error
	Save(values ...*entity.RegistryRepositoryDeployRuleMatchLog) error
	First() (*entity.RegistryRepositoryDeployRuleMatchLog, error)
	Take() (*entity.RegistryRepositoryDeployRuleMatchLog, error)
	Last() (*entity.RegistryRepositoryDeployRuleMatchLog, error)
	Find() ([]*entity.RegistryRepositoryDeployRuleMatchLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryRepositoryDeployRuleMatchLog, err error)
	FindInBatches(result *[]*entity.RegistryRepositoryDeployRuleMatchLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.RegistryRepositoryDeployRuleMatchLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRegistryRepositoryDeployRuleMatchLogDo
	Assign(attrs ...field.AssignExpr) IRegistryRepositoryDeployRuleMatchLogDo
	Joins(fields ...field.RelationField) IRegistryRepositoryDeployRuleMatchLogDo
	Preload(fields ...field.RelationField) IRegistryRepositoryDeployRuleMatchLogDo
	FirstOrInit() (*entity.RegistryRepositoryDeployRuleMatchLog, error)
	FirstOrCreate() (*entity.RegistryRepositoryDeployRuleMatchLog, error)
	FindByPage(offset int, limit int) (result []*entity.RegistryRepositoryDeployRuleMatchLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRegistryRepositoryDeployRuleMatchLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r registryRepositoryDeployRuleMatchLogDo) Debug() IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Debug())
}

func (r registryRepositoryDeployRuleMatchLogDo) WithContext(ctx context.Context) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r registryRepositoryDeployRuleMatchLogDo) ReadDB() IRegistryRepositoryDeployRuleMatchLogDo {
	return r.Clauses(dbresolver.Read)
}

func (r registryRepositoryDeployRuleMatchLogDo) WriteDB() IRegistryRepositoryDeployRuleMatchLogDo {
	return r.Clauses(dbresolver.Write)
}

func (r registryRepositoryDeployRuleMatchLogDo) Session(config *gorm.Session) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Session(config))
}

func (r registryRepositoryDeployRuleMatchLogDo) Clauses(conds ...clause.Expression) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Returning(value interface{}, columns ...string) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Not(conds ...gen.Condition) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Or(conds ...gen.Condition) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Select(conds ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Where(conds ...gen.Condition) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Order(conds ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Distinct(cols ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Omit(cols ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Join(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r registryRepositoryDeployRuleMatchLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r registryRepositoryDeployRuleMatchLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Group(cols ...field.Expr) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Having(conds ...gen.Condition) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Limit(limit int) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r registryRepositoryDeployRuleMatchLogDo) Offset(offset int) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r registryRepositoryDeployRuleMatchLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Unscoped() IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Unscoped())
}

func (r registryRepositoryDeployRuleMatchLogDo) Create(values ...*entity.RegistryRepositoryDeployRuleMatchLog) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r registryRepositoryDeployRuleMatchLogDo) CreateInBatches(values []*entity.RegistryRepositoryDeployRuleMatchLog, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r registryRepositoryDeployRuleMatchLogDo) Save(values ...*entity.RegistryRepositoryDeployRuleMatchLog) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r registryRepositoryDeployRuleMatchLogDo) First() (*entity.RegistryRepositoryDeployRuleMatchLog, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryDeployRuleMatchLog), nil
	}
}

func (r registryRepositoryDeployRuleMatchLogDo) Take() (*entity.RegistryRepositoryDeployRuleMatchLog, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryDeployRuleMatchLog), nil
	}
}

func (r registryRepositoryDeployRuleMatchLogDo) Last() (*entity.RegistryRepositoryDeployRuleMatchLog, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryDeployRuleMatchLog), nil
	}
}

func (r registryRepositoryDeployRuleMatchLogDo) Find() ([]*entity.RegistryRepositoryDeployRuleMatchLog, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RegistryRepositoryDeployRuleMatchLog), err
}

func (r registryRepositoryDeployRuleMatchLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryRepositoryDeployRuleMatchLog, err error) {
	buf := make([]*entity.RegistryRepositoryDeployRuleMatchLog, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r registryRepositoryDeployRuleMatchLogDo) FindInBatches(result *[]*entity.RegistryRepositoryDeployRuleMatchLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r registryRepositoryDeployRuleMatchLogDo) Attrs(attrs ...field.AssignExpr) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Assign(attrs ...field.AssignExpr) IRegistryRepositoryDeployRuleMatchLogDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r registryRepositoryDeployRuleMatchLogDo) Joins(fields ...field.RelationField) IRegistryRepositoryDeployRuleMatchLogDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r registryRepositoryDeployRuleMatchLogDo) Preload(fields ...field.RelationField) IRegistryRepositoryDeployRuleMatchLogDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r registryRepositoryDeployRuleMatchLogDo) FirstOrInit() (*entity.RegistryRepositoryDeployRuleMatchLog, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryDeployRuleMatchLog), nil
	}
}

func (r registryRepositoryDeployRuleMatchLogDo) FirstOrCreate() (*entity.RegistryRepositoryDeployRuleMatchLog, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryDeployRuleMatchLog), nil
	}
}

func (r registryRepositoryDeployRuleMatchLogDo) FindByPage(offset int, limit int) (result []*entity.RegistryRepositoryDeployRuleMatchLog, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r registryRepositoryDeployRuleMatchLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r registryRepositoryDeployRuleMatchLogDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r registryRepositoryDeployRuleMatchLogDo) Delete(models ...*entity.RegistryRepositoryDeployRuleMatchLog) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *registryRepositoryDeployRuleMatchLogDo) withDO(do gen.Dao) *registryRepositoryDeployRuleMatchLogDo {
	r.DO = *do.(*gen.DO)
	return r
}
