// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-zpk/common/entity"
)

func newRegistryNamespace(db *gorm.DB, opts ...gen.DOOption) registryNamespace {
	_registryNamespace := registryNamespace{}

	_registryNamespace.registryNamespaceDo.UseDB(db, opts...)
	_registryNamespace.registryNamespaceDo.UseModel(&entity.RegistryNamespace{})

	tableName := _registryNamespace.registryNamespaceDo.TableName()
	_registryNamespace.ALL = field.NewAsterisk(tableName)
	_registryNamespace.ID = field.NewInt32(tableName, "id")
	_registryNamespace.UserID = field.NewInt32(tableName, "user_id")
	_registryNamespace.Name = field.NewString(tableName, "name")
	_registryNamespace.VisibleType = field.NewInt32(tableName, "visible_type")
	_registryNamespace.CreatedAt = field.NewTime(tableName, "created_at")
	_registryNamespace.UpdatedAt = field.NewTime(tableName, "updated_at")
	_registryNamespace.DeletedAt = field.NewField(tableName, "deleted_at")

	_registryNamespace.fillFieldMap()

	return _registryNamespace
}

type registryNamespace struct {
	registryNamespaceDo

	ALL         field.Asterisk
	ID          field.Int32
	UserID      field.Int32
	Name        field.String
	VisibleType field.Int32
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (r registryNamespace) Table(newTableName string) *registryNamespace {
	r.registryNamespaceDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r registryNamespace) As(alias string) *registryNamespace {
	r.registryNamespaceDo.DO = *(r.registryNamespaceDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *registryNamespace) updateTableName(table string) *registryNamespace {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.UserID = field.NewInt32(table, "user_id")
	r.Name = field.NewString(table, "name")
	r.VisibleType = field.NewInt32(table, "visible_type")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *registryNamespace) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *registryNamespace) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["name"] = r.Name
	r.fieldMap["visible_type"] = r.VisibleType
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r registryNamespace) clone(db *gorm.DB) registryNamespace {
	r.registryNamespaceDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r registryNamespace) replaceDB(db *gorm.DB) registryNamespace {
	r.registryNamespaceDo.ReplaceDB(db)
	return r
}

type registryNamespaceDo struct{ gen.DO }

type IRegistryNamespaceDo interface {
	gen.SubQuery
	Debug() IRegistryNamespaceDo
	WithContext(ctx context.Context) IRegistryNamespaceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRegistryNamespaceDo
	WriteDB() IRegistryNamespaceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRegistryNamespaceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRegistryNamespaceDo
	Not(conds ...gen.Condition) IRegistryNamespaceDo
	Or(conds ...gen.Condition) IRegistryNamespaceDo
	Select(conds ...field.Expr) IRegistryNamespaceDo
	Where(conds ...gen.Condition) IRegistryNamespaceDo
	Order(conds ...field.Expr) IRegistryNamespaceDo
	Distinct(cols ...field.Expr) IRegistryNamespaceDo
	Omit(cols ...field.Expr) IRegistryNamespaceDo
	Join(table schema.Tabler, on ...field.Expr) IRegistryNamespaceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryNamespaceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRegistryNamespaceDo
	Group(cols ...field.Expr) IRegistryNamespaceDo
	Having(conds ...gen.Condition) IRegistryNamespaceDo
	Limit(limit int) IRegistryNamespaceDo
	Offset(offset int) IRegistryNamespaceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryNamespaceDo
	Unscoped() IRegistryNamespaceDo
	Create(values ...*entity.RegistryNamespace) error
	CreateInBatches(values []*entity.RegistryNamespace, batchSize int) error
	Save(values ...*entity.RegistryNamespace) error
	First() (*entity.RegistryNamespace, error)
	Take() (*entity.RegistryNamespace, error)
	Last() (*entity.RegistryNamespace, error)
	Find() ([]*entity.RegistryNamespace, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryNamespace, err error)
	FindInBatches(result *[]*entity.RegistryNamespace, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.RegistryNamespace) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRegistryNamespaceDo
	Assign(attrs ...field.AssignExpr) IRegistryNamespaceDo
	Joins(fields ...field.RelationField) IRegistryNamespaceDo
	Preload(fields ...field.RelationField) IRegistryNamespaceDo
	FirstOrInit() (*entity.RegistryNamespace, error)
	FirstOrCreate() (*entity.RegistryNamespace, error)
	FindByPage(offset int, limit int) (result []*entity.RegistryNamespace, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRegistryNamespaceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r registryNamespaceDo) Debug() IRegistryNamespaceDo {
	return r.withDO(r.DO.Debug())
}

func (r registryNamespaceDo) WithContext(ctx context.Context) IRegistryNamespaceDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r registryNamespaceDo) ReadDB() IRegistryNamespaceDo {
	return r.Clauses(dbresolver.Read)
}

func (r registryNamespaceDo) WriteDB() IRegistryNamespaceDo {
	return r.Clauses(dbresolver.Write)
}

func (r registryNamespaceDo) Session(config *gorm.Session) IRegistryNamespaceDo {
	return r.withDO(r.DO.Session(config))
}

func (r registryNamespaceDo) Clauses(conds ...clause.Expression) IRegistryNamespaceDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r registryNamespaceDo) Returning(value interface{}, columns ...string) IRegistryNamespaceDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r registryNamespaceDo) Not(conds ...gen.Condition) IRegistryNamespaceDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r registryNamespaceDo) Or(conds ...gen.Condition) IRegistryNamespaceDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r registryNamespaceDo) Select(conds ...field.Expr) IRegistryNamespaceDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r registryNamespaceDo) Where(conds ...gen.Condition) IRegistryNamespaceDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r registryNamespaceDo) Order(conds ...field.Expr) IRegistryNamespaceDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r registryNamespaceDo) Distinct(cols ...field.Expr) IRegistryNamespaceDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r registryNamespaceDo) Omit(cols ...field.Expr) IRegistryNamespaceDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r registryNamespaceDo) Join(table schema.Tabler, on ...field.Expr) IRegistryNamespaceDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r registryNamespaceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryNamespaceDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r registryNamespaceDo) RightJoin(table schema.Tabler, on ...field.Expr) IRegistryNamespaceDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r registryNamespaceDo) Group(cols ...field.Expr) IRegistryNamespaceDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r registryNamespaceDo) Having(conds ...gen.Condition) IRegistryNamespaceDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r registryNamespaceDo) Limit(limit int) IRegistryNamespaceDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r registryNamespaceDo) Offset(offset int) IRegistryNamespaceDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r registryNamespaceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryNamespaceDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r registryNamespaceDo) Unscoped() IRegistryNamespaceDo {
	return r.withDO(r.DO.Unscoped())
}

func (r registryNamespaceDo) Create(values ...*entity.RegistryNamespace) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r registryNamespaceDo) CreateInBatches(values []*entity.RegistryNamespace, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r registryNamespaceDo) Save(values ...*entity.RegistryNamespace) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r registryNamespaceDo) First() (*entity.RegistryNamespace, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryNamespace), nil
	}
}

func (r registryNamespaceDo) Take() (*entity.RegistryNamespace, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryNamespace), nil
	}
}

func (r registryNamespaceDo) Last() (*entity.RegistryNamespace, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryNamespace), nil
	}
}

func (r registryNamespaceDo) Find() ([]*entity.RegistryNamespace, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RegistryNamespace), err
}

func (r registryNamespaceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryNamespace, err error) {
	buf := make([]*entity.RegistryNamespace, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r registryNamespaceDo) FindInBatches(result *[]*entity.RegistryNamespace, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r registryNamespaceDo) Attrs(attrs ...field.AssignExpr) IRegistryNamespaceDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r registryNamespaceDo) Assign(attrs ...field.AssignExpr) IRegistryNamespaceDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r registryNamespaceDo) Joins(fields ...field.RelationField) IRegistryNamespaceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r registryNamespaceDo) Preload(fields ...field.RelationField) IRegistryNamespaceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r registryNamespaceDo) FirstOrInit() (*entity.RegistryNamespace, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryNamespace), nil
	}
}

func (r registryNamespaceDo) FirstOrCreate() (*entity.RegistryNamespace, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryNamespace), nil
	}
}

func (r registryNamespaceDo) FindByPage(offset int, limit int) (result []*entity.RegistryNamespace, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r registryNamespaceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r registryNamespaceDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r registryNamespaceDo) Delete(models ...*entity.RegistryNamespace) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *registryNamespaceDo) withDO(do gen.Dao) *registryNamespaceDo {
	r.DO = *do.(*gen.DO)
	return r
}
