// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-zpk/common/entity"
)

func newRegistryRepository(db *gorm.DB, opts ...gen.DOOption) registryRepository {
	_registryRepository := registryRepository{}

	_registryRepository.registryRepositoryDo.UseDB(db, opts...)
	_registryRepository.registryRepositoryDo.UseModel(&entity.RegistryRepository{})

	tableName := _registryRepository.registryRepositoryDo.TableName()
	_registryRepository.ALL = field.NewAsterisk(tableName)
	_registryRepository.ID = field.NewInt32(tableName, "id")
	_registryRepository.UserID = field.NewInt32(tableName, "user_id")
	_registryRepository.Name = field.NewString(tableName, "name")
	_registryRepository.Registry = field.NewString(tableName, "registry")
	_registryRepository.Namespace = field.NewString(tableName, "namespace")
	_registryRepository.VisibleType = field.NewInt32(tableName, "visible_type")
	_registryRepository.PullNum = field.NewInt32(tableName, "pull_num")
	_registryRepository.Desc = field.NewString(tableName, "desc")
	_registryRepository.CreatedAt = field.NewTime(tableName, "created_at")
	_registryRepository.UpdatedAt = field.NewTime(tableName, "updated_at")
	_registryRepository.DeletedAt = field.NewField(tableName, "deleted_at")

	_registryRepository.fillFieldMap()

	return _registryRepository
}

type registryRepository struct {
	registryRepositoryDo

	ALL         field.Asterisk
	ID          field.Int32
	UserID      field.Int32
	Name        field.String
	Registry    field.String
	Namespace   field.String
	VisibleType field.Int32
	PullNum     field.Int32
	Desc        field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (r registryRepository) Table(newTableName string) *registryRepository {
	r.registryRepositoryDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r registryRepository) As(alias string) *registryRepository {
	r.registryRepositoryDo.DO = *(r.registryRepositoryDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *registryRepository) updateTableName(table string) *registryRepository {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.UserID = field.NewInt32(table, "user_id")
	r.Name = field.NewString(table, "name")
	r.Registry = field.NewString(table, "registry")
	r.Namespace = field.NewString(table, "namespace")
	r.VisibleType = field.NewInt32(table, "visible_type")
	r.PullNum = field.NewInt32(table, "pull_num")
	r.Desc = field.NewString(table, "desc")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *registryRepository) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *registryRepository) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 11)
	r.fieldMap["id"] = r.ID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["name"] = r.Name
	r.fieldMap["registry"] = r.Registry
	r.fieldMap["namespace"] = r.Namespace
	r.fieldMap["visible_type"] = r.VisibleType
	r.fieldMap["pull_num"] = r.PullNum
	r.fieldMap["desc"] = r.Desc
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r registryRepository) clone(db *gorm.DB) registryRepository {
	r.registryRepositoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r registryRepository) replaceDB(db *gorm.DB) registryRepository {
	r.registryRepositoryDo.ReplaceDB(db)
	return r
}

type registryRepositoryDo struct{ gen.DO }

type IRegistryRepositoryDo interface {
	gen.SubQuery
	Debug() IRegistryRepositoryDo
	WithContext(ctx context.Context) IRegistryRepositoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRegistryRepositoryDo
	WriteDB() IRegistryRepositoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRegistryRepositoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRegistryRepositoryDo
	Not(conds ...gen.Condition) IRegistryRepositoryDo
	Or(conds ...gen.Condition) IRegistryRepositoryDo
	Select(conds ...field.Expr) IRegistryRepositoryDo
	Where(conds ...gen.Condition) IRegistryRepositoryDo
	Order(conds ...field.Expr) IRegistryRepositoryDo
	Distinct(cols ...field.Expr) IRegistryRepositoryDo
	Omit(cols ...field.Expr) IRegistryRepositoryDo
	Join(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDo
	Group(cols ...field.Expr) IRegistryRepositoryDo
	Having(conds ...gen.Condition) IRegistryRepositoryDo
	Limit(limit int) IRegistryRepositoryDo
	Offset(offset int) IRegistryRepositoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryRepositoryDo
	Unscoped() IRegistryRepositoryDo
	Create(values ...*entity.RegistryRepository) error
	CreateInBatches(values []*entity.RegistryRepository, batchSize int) error
	Save(values ...*entity.RegistryRepository) error
	First() (*entity.RegistryRepository, error)
	Take() (*entity.RegistryRepository, error)
	Last() (*entity.RegistryRepository, error)
	Find() ([]*entity.RegistryRepository, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryRepository, err error)
	FindInBatches(result *[]*entity.RegistryRepository, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.RegistryRepository) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRegistryRepositoryDo
	Assign(attrs ...field.AssignExpr) IRegistryRepositoryDo
	Joins(fields ...field.RelationField) IRegistryRepositoryDo
	Preload(fields ...field.RelationField) IRegistryRepositoryDo
	FirstOrInit() (*entity.RegistryRepository, error)
	FirstOrCreate() (*entity.RegistryRepository, error)
	FindByPage(offset int, limit int) (result []*entity.RegistryRepository, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRegistryRepositoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r registryRepositoryDo) Debug() IRegistryRepositoryDo {
	return r.withDO(r.DO.Debug())
}

func (r registryRepositoryDo) WithContext(ctx context.Context) IRegistryRepositoryDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r registryRepositoryDo) ReadDB() IRegistryRepositoryDo {
	return r.Clauses(dbresolver.Read)
}

func (r registryRepositoryDo) WriteDB() IRegistryRepositoryDo {
	return r.Clauses(dbresolver.Write)
}

func (r registryRepositoryDo) Session(config *gorm.Session) IRegistryRepositoryDo {
	return r.withDO(r.DO.Session(config))
}

func (r registryRepositoryDo) Clauses(conds ...clause.Expression) IRegistryRepositoryDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r registryRepositoryDo) Returning(value interface{}, columns ...string) IRegistryRepositoryDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r registryRepositoryDo) Not(conds ...gen.Condition) IRegistryRepositoryDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r registryRepositoryDo) Or(conds ...gen.Condition) IRegistryRepositoryDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r registryRepositoryDo) Select(conds ...field.Expr) IRegistryRepositoryDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r registryRepositoryDo) Where(conds ...gen.Condition) IRegistryRepositoryDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r registryRepositoryDo) Order(conds ...field.Expr) IRegistryRepositoryDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r registryRepositoryDo) Distinct(cols ...field.Expr) IRegistryRepositoryDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r registryRepositoryDo) Omit(cols ...field.Expr) IRegistryRepositoryDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r registryRepositoryDo) Join(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r registryRepositoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r registryRepositoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r registryRepositoryDo) Group(cols ...field.Expr) IRegistryRepositoryDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r registryRepositoryDo) Having(conds ...gen.Condition) IRegistryRepositoryDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r registryRepositoryDo) Limit(limit int) IRegistryRepositoryDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r registryRepositoryDo) Offset(offset int) IRegistryRepositoryDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r registryRepositoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryRepositoryDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r registryRepositoryDo) Unscoped() IRegistryRepositoryDo {
	return r.withDO(r.DO.Unscoped())
}

func (r registryRepositoryDo) Create(values ...*entity.RegistryRepository) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r registryRepositoryDo) CreateInBatches(values []*entity.RegistryRepository, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r registryRepositoryDo) Save(values ...*entity.RegistryRepository) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r registryRepositoryDo) First() (*entity.RegistryRepository, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepository), nil
	}
}

func (r registryRepositoryDo) Take() (*entity.RegistryRepository, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepository), nil
	}
}

func (r registryRepositoryDo) Last() (*entity.RegistryRepository, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepository), nil
	}
}

func (r registryRepositoryDo) Find() ([]*entity.RegistryRepository, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RegistryRepository), err
}

func (r registryRepositoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryRepository, err error) {
	buf := make([]*entity.RegistryRepository, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r registryRepositoryDo) FindInBatches(result *[]*entity.RegistryRepository, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r registryRepositoryDo) Attrs(attrs ...field.AssignExpr) IRegistryRepositoryDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r registryRepositoryDo) Assign(attrs ...field.AssignExpr) IRegistryRepositoryDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r registryRepositoryDo) Joins(fields ...field.RelationField) IRegistryRepositoryDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r registryRepositoryDo) Preload(fields ...field.RelationField) IRegistryRepositoryDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r registryRepositoryDo) FirstOrInit() (*entity.RegistryRepository, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepository), nil
	}
}

func (r registryRepositoryDo) FirstOrCreate() (*entity.RegistryRepository, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepository), nil
	}
}

func (r registryRepositoryDo) FindByPage(offset int, limit int) (result []*entity.RegistryRepository, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r registryRepositoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r registryRepositoryDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r registryRepositoryDo) Delete(models ...*entity.RegistryRepository) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *registryRepositoryDo) withDO(do gen.Dao) *registryRepositoryDo {
	r.DO = *do.(*gen.DO)
	return r
}
