// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-zpk/common/entity"
)

func newVersion(db *gorm.DB, opts ...gen.DOOption) version {
	_version := version{}

	_version.versionDo.UseDB(db, opts...)
	_version.versionDo.UseModel(&entity.Version{})

	tableName := _version.versionDo.TableName()
	_version.ALL = field.NewAsterisk(tableName)
	_version.ID = field.NewInt32(tableName, "id")
	_version.FormulaID = field.NewInt32(tableName, "formula_id")
	_version.Name = field.NewString(tableName, "name")
	_version.Description = field.NewString(tableName, "description")
	_version.PublishStatus = field.NewInt32(tableName, "publish_status")
	_version.PublishFailReason = field.NewString(tableName, "publish_fail_reason")
	_version.CreatedAt = field.NewTime(tableName, "created_at")

	_version.fillFieldMap()

	return _version
}

type version struct {
	versionDo

	ALL               field.Asterisk
	ID                field.Int32
	FormulaID         field.Int32
	Name              field.String
	Description       field.String
	PublishStatus     field.Int32
	PublishFailReason field.String
	CreatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (v version) Table(newTableName string) *version {
	v.versionDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v version) As(alias string) *version {
	v.versionDo.DO = *(v.versionDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *version) updateTableName(table string) *version {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt32(table, "id")
	v.FormulaID = field.NewInt32(table, "formula_id")
	v.Name = field.NewString(table, "name")
	v.Description = field.NewString(table, "description")
	v.PublishStatus = field.NewInt32(table, "publish_status")
	v.PublishFailReason = field.NewString(table, "publish_fail_reason")
	v.CreatedAt = field.NewTime(table, "created_at")

	v.fillFieldMap()

	return v
}

func (v *version) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *version) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 7)
	v.fieldMap["id"] = v.ID
	v.fieldMap["formula_id"] = v.FormulaID
	v.fieldMap["name"] = v.Name
	v.fieldMap["description"] = v.Description
	v.fieldMap["publish_status"] = v.PublishStatus
	v.fieldMap["publish_fail_reason"] = v.PublishFailReason
	v.fieldMap["created_at"] = v.CreatedAt
}

func (v version) clone(db *gorm.DB) version {
	v.versionDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v version) replaceDB(db *gorm.DB) version {
	v.versionDo.ReplaceDB(db)
	return v
}

type versionDo struct{ gen.DO }

type IVersionDo interface {
	gen.SubQuery
	Debug() IVersionDo
	WithContext(ctx context.Context) IVersionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVersionDo
	WriteDB() IVersionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVersionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVersionDo
	Not(conds ...gen.Condition) IVersionDo
	Or(conds ...gen.Condition) IVersionDo
	Select(conds ...field.Expr) IVersionDo
	Where(conds ...gen.Condition) IVersionDo
	Order(conds ...field.Expr) IVersionDo
	Distinct(cols ...field.Expr) IVersionDo
	Omit(cols ...field.Expr) IVersionDo
	Join(table schema.Tabler, on ...field.Expr) IVersionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVersionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVersionDo
	Group(cols ...field.Expr) IVersionDo
	Having(conds ...gen.Condition) IVersionDo
	Limit(limit int) IVersionDo
	Offset(offset int) IVersionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVersionDo
	Unscoped() IVersionDo
	Create(values ...*entity.Version) error
	CreateInBatches(values []*entity.Version, batchSize int) error
	Save(values ...*entity.Version) error
	First() (*entity.Version, error)
	Take() (*entity.Version, error)
	Last() (*entity.Version, error)
	Find() ([]*entity.Version, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Version, err error)
	FindInBatches(result *[]*entity.Version, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.Version) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVersionDo
	Assign(attrs ...field.AssignExpr) IVersionDo
	Joins(fields ...field.RelationField) IVersionDo
	Preload(fields ...field.RelationField) IVersionDo
	FirstOrInit() (*entity.Version, error)
	FirstOrCreate() (*entity.Version, error)
	FindByPage(offset int, limit int) (result []*entity.Version, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVersionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v versionDo) Debug() IVersionDo {
	return v.withDO(v.DO.Debug())
}

func (v versionDo) WithContext(ctx context.Context) IVersionDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v versionDo) ReadDB() IVersionDo {
	return v.Clauses(dbresolver.Read)
}

func (v versionDo) WriteDB() IVersionDo {
	return v.Clauses(dbresolver.Write)
}

func (v versionDo) Session(config *gorm.Session) IVersionDo {
	return v.withDO(v.DO.Session(config))
}

func (v versionDo) Clauses(conds ...clause.Expression) IVersionDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v versionDo) Returning(value interface{}, columns ...string) IVersionDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v versionDo) Not(conds ...gen.Condition) IVersionDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v versionDo) Or(conds ...gen.Condition) IVersionDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v versionDo) Select(conds ...field.Expr) IVersionDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v versionDo) Where(conds ...gen.Condition) IVersionDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v versionDo) Order(conds ...field.Expr) IVersionDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v versionDo) Distinct(cols ...field.Expr) IVersionDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v versionDo) Omit(cols ...field.Expr) IVersionDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v versionDo) Join(table schema.Tabler, on ...field.Expr) IVersionDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v versionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVersionDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v versionDo) RightJoin(table schema.Tabler, on ...field.Expr) IVersionDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v versionDo) Group(cols ...field.Expr) IVersionDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v versionDo) Having(conds ...gen.Condition) IVersionDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v versionDo) Limit(limit int) IVersionDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v versionDo) Offset(offset int) IVersionDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v versionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVersionDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v versionDo) Unscoped() IVersionDo {
	return v.withDO(v.DO.Unscoped())
}

func (v versionDo) Create(values ...*entity.Version) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v versionDo) CreateInBatches(values []*entity.Version, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v versionDo) Save(values ...*entity.Version) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v versionDo) First() (*entity.Version, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Version), nil
	}
}

func (v versionDo) Take() (*entity.Version, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Version), nil
	}
}

func (v versionDo) Last() (*entity.Version, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Version), nil
	}
}

func (v versionDo) Find() ([]*entity.Version, error) {
	result, err := v.DO.Find()
	return result.([]*entity.Version), err
}

func (v versionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Version, err error) {
	buf := make([]*entity.Version, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v versionDo) FindInBatches(result *[]*entity.Version, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v versionDo) Attrs(attrs ...field.AssignExpr) IVersionDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v versionDo) Assign(attrs ...field.AssignExpr) IVersionDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v versionDo) Joins(fields ...field.RelationField) IVersionDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v versionDo) Preload(fields ...field.RelationField) IVersionDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v versionDo) FirstOrInit() (*entity.Version, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Version), nil
	}
}

func (v versionDo) FirstOrCreate() (*entity.Version, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Version), nil
	}
}

func (v versionDo) FindByPage(offset int, limit int) (result []*entity.Version, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v versionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v versionDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v versionDo) Delete(models ...*entity.Version) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *versionDo) withDO(do gen.Dao) *versionDo {
	v.DO = *do.(*gen.DO)
	return v
}
