// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-zpk/common/entity"
)

func newRegistryUser(db *gorm.DB, opts ...gen.DOOption) registryUser {
	_registryUser := registryUser{}

	_registryUser.registryUserDo.UseDB(db, opts...)
	_registryUser.registryUserDo.UseModel(&entity.RegistryUser{})

	tableName := _registryUser.registryUserDo.TableName()
	_registryUser.ALL = field.NewAsterisk(tableName)
	_registryUser.ID = field.NewInt32(tableName, "id")
	_registryUser.Username = field.NewString(tableName, "username")
	_registryUser.Password = field.NewString(tableName, "password")
	_registryUser.Desc = field.NewString(tableName, "desc")
	_registryUser.Type = field.NewInt32(tableName, "type")
	_registryUser.ExpireDays = field.NewInt32(tableName, "expire_days")
	_registryUser.Setting = field.NewField(tableName, "setting")
	_registryUser.Role = field.NewString(tableName, "role")
	_registryUser.CreatedAt = field.NewTime(tableName, "created_at")
	_registryUser.UpdatedAt = field.NewTime(tableName, "updated_at")

	_registryUser.fillFieldMap()

	return _registryUser
}

type registryUser struct {
	registryUserDo

	ALL        field.Asterisk
	ID         field.Int32
	Username   field.String
	Password   field.String
	Desc       field.String
	Type       field.Int32
	ExpireDays field.Int32
	Setting    field.Field
	Role       field.String
	CreatedAt  field.Time
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (r registryUser) Table(newTableName string) *registryUser {
	r.registryUserDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r registryUser) As(alias string) *registryUser {
	r.registryUserDo.DO = *(r.registryUserDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *registryUser) updateTableName(table string) *registryUser {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.Username = field.NewString(table, "username")
	r.Password = field.NewString(table, "password")
	r.Desc = field.NewString(table, "desc")
	r.Type = field.NewInt32(table, "type")
	r.ExpireDays = field.NewInt32(table, "expire_days")
	r.Setting = field.NewField(table, "setting")
	r.Role = field.NewString(table, "role")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *registryUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *registryUser) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 10)
	r.fieldMap["id"] = r.ID
	r.fieldMap["username"] = r.Username
	r.fieldMap["password"] = r.Password
	r.fieldMap["desc"] = r.Desc
	r.fieldMap["type"] = r.Type
	r.fieldMap["expire_days"] = r.ExpireDays
	r.fieldMap["setting"] = r.Setting
	r.fieldMap["role"] = r.Role
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r registryUser) clone(db *gorm.DB) registryUser {
	r.registryUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r registryUser) replaceDB(db *gorm.DB) registryUser {
	r.registryUserDo.ReplaceDB(db)
	return r
}

type registryUserDo struct{ gen.DO }

type IRegistryUserDo interface {
	gen.SubQuery
	Debug() IRegistryUserDo
	WithContext(ctx context.Context) IRegistryUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRegistryUserDo
	WriteDB() IRegistryUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRegistryUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRegistryUserDo
	Not(conds ...gen.Condition) IRegistryUserDo
	Or(conds ...gen.Condition) IRegistryUserDo
	Select(conds ...field.Expr) IRegistryUserDo
	Where(conds ...gen.Condition) IRegistryUserDo
	Order(conds ...field.Expr) IRegistryUserDo
	Distinct(cols ...field.Expr) IRegistryUserDo
	Omit(cols ...field.Expr) IRegistryUserDo
	Join(table schema.Tabler, on ...field.Expr) IRegistryUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRegistryUserDo
	Group(cols ...field.Expr) IRegistryUserDo
	Having(conds ...gen.Condition) IRegistryUserDo
	Limit(limit int) IRegistryUserDo
	Offset(offset int) IRegistryUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryUserDo
	Unscoped() IRegistryUserDo
	Create(values ...*entity.RegistryUser) error
	CreateInBatches(values []*entity.RegistryUser, batchSize int) error
	Save(values ...*entity.RegistryUser) error
	First() (*entity.RegistryUser, error)
	Take() (*entity.RegistryUser, error)
	Last() (*entity.RegistryUser, error)
	Find() ([]*entity.RegistryUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryUser, err error)
	FindInBatches(result *[]*entity.RegistryUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.RegistryUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRegistryUserDo
	Assign(attrs ...field.AssignExpr) IRegistryUserDo
	Joins(fields ...field.RelationField) IRegistryUserDo
	Preload(fields ...field.RelationField) IRegistryUserDo
	FirstOrInit() (*entity.RegistryUser, error)
	FirstOrCreate() (*entity.RegistryUser, error)
	FindByPage(offset int, limit int) (result []*entity.RegistryUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRegistryUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r registryUserDo) Debug() IRegistryUserDo {
	return r.withDO(r.DO.Debug())
}

func (r registryUserDo) WithContext(ctx context.Context) IRegistryUserDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r registryUserDo) ReadDB() IRegistryUserDo {
	return r.Clauses(dbresolver.Read)
}

func (r registryUserDo) WriteDB() IRegistryUserDo {
	return r.Clauses(dbresolver.Write)
}

func (r registryUserDo) Session(config *gorm.Session) IRegistryUserDo {
	return r.withDO(r.DO.Session(config))
}

func (r registryUserDo) Clauses(conds ...clause.Expression) IRegistryUserDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r registryUserDo) Returning(value interface{}, columns ...string) IRegistryUserDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r registryUserDo) Not(conds ...gen.Condition) IRegistryUserDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r registryUserDo) Or(conds ...gen.Condition) IRegistryUserDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r registryUserDo) Select(conds ...field.Expr) IRegistryUserDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r registryUserDo) Where(conds ...gen.Condition) IRegistryUserDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r registryUserDo) Order(conds ...field.Expr) IRegistryUserDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r registryUserDo) Distinct(cols ...field.Expr) IRegistryUserDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r registryUserDo) Omit(cols ...field.Expr) IRegistryUserDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r registryUserDo) Join(table schema.Tabler, on ...field.Expr) IRegistryUserDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r registryUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryUserDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r registryUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IRegistryUserDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r registryUserDo) Group(cols ...field.Expr) IRegistryUserDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r registryUserDo) Having(conds ...gen.Condition) IRegistryUserDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r registryUserDo) Limit(limit int) IRegistryUserDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r registryUserDo) Offset(offset int) IRegistryUserDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r registryUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryUserDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r registryUserDo) Unscoped() IRegistryUserDo {
	return r.withDO(r.DO.Unscoped())
}

func (r registryUserDo) Create(values ...*entity.RegistryUser) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r registryUserDo) CreateInBatches(values []*entity.RegistryUser, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r registryUserDo) Save(values ...*entity.RegistryUser) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r registryUserDo) First() (*entity.RegistryUser, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryUser), nil
	}
}

func (r registryUserDo) Take() (*entity.RegistryUser, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryUser), nil
	}
}

func (r registryUserDo) Last() (*entity.RegistryUser, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryUser), nil
	}
}

func (r registryUserDo) Find() ([]*entity.RegistryUser, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RegistryUser), err
}

func (r registryUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryUser, err error) {
	buf := make([]*entity.RegistryUser, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r registryUserDo) FindInBatches(result *[]*entity.RegistryUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r registryUserDo) Attrs(attrs ...field.AssignExpr) IRegistryUserDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r registryUserDo) Assign(attrs ...field.AssignExpr) IRegistryUserDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r registryUserDo) Joins(fields ...field.RelationField) IRegistryUserDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r registryUserDo) Preload(fields ...field.RelationField) IRegistryUserDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r registryUserDo) FirstOrInit() (*entity.RegistryUser, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryUser), nil
	}
}

func (r registryUserDo) FirstOrCreate() (*entity.RegistryUser, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryUser), nil
	}
}

func (r registryUserDo) FindByPage(offset int, limit int) (result []*entity.RegistryUser, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r registryUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r registryUserDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r registryUserDo) Delete(models ...*entity.RegistryUser) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *registryUserDo) withDO(do gen.Dao) *registryUserDo {
	r.DO = *do.(*gen.DO)
	return r
}
