// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-zpk/common/entity"
)

func newRegistryRepositoryTag(db *gorm.DB, opts ...gen.DOOption) registryRepositoryTag {
	_registryRepositoryTag := registryRepositoryTag{}

	_registryRepositoryTag.registryRepositoryTagDo.UseDB(db, opts...)
	_registryRepositoryTag.registryRepositoryTagDo.UseModel(&entity.RegistryRepositoryTag{})

	tableName := _registryRepositoryTag.registryRepositoryTagDo.TableName()
	_registryRepositoryTag.ALL = field.NewAsterisk(tableName)
	_registryRepositoryTag.ID = field.NewInt32(tableName, "id")
	_registryRepositoryTag.RepositoryID = field.NewInt32(tableName, "repository_id")
	_registryRepositoryTag.Name = field.NewString(tableName, "name")
	_registryRepositoryTag.CrearedAt = field.NewTime(tableName, "creared_at")
	_registryRepositoryTag.LatestPushAt = field.NewTime(tableName, "latest_push_at")

	_registryRepositoryTag.fillFieldMap()

	return _registryRepositoryTag
}

type registryRepositoryTag struct {
	registryRepositoryTagDo

	ALL          field.Asterisk
	ID           field.Int32
	RepositoryID field.Int32
	Name         field.String
	CrearedAt    field.Time
	LatestPushAt field.Time

	fieldMap map[string]field.Expr
}

func (r registryRepositoryTag) Table(newTableName string) *registryRepositoryTag {
	r.registryRepositoryTagDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r registryRepositoryTag) As(alias string) *registryRepositoryTag {
	r.registryRepositoryTagDo.DO = *(r.registryRepositoryTagDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *registryRepositoryTag) updateTableName(table string) *registryRepositoryTag {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.RepositoryID = field.NewInt32(table, "repository_id")
	r.Name = field.NewString(table, "name")
	r.CrearedAt = field.NewTime(table, "creared_at")
	r.LatestPushAt = field.NewTime(table, "latest_push_at")

	r.fillFieldMap()

	return r
}

func (r *registryRepositoryTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *registryRepositoryTag) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 5)
	r.fieldMap["id"] = r.ID
	r.fieldMap["repository_id"] = r.RepositoryID
	r.fieldMap["name"] = r.Name
	r.fieldMap["creared_at"] = r.CrearedAt
	r.fieldMap["latest_push_at"] = r.LatestPushAt
}

func (r registryRepositoryTag) clone(db *gorm.DB) registryRepositoryTag {
	r.registryRepositoryTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r registryRepositoryTag) replaceDB(db *gorm.DB) registryRepositoryTag {
	r.registryRepositoryTagDo.ReplaceDB(db)
	return r
}

type registryRepositoryTagDo struct{ gen.DO }

type IRegistryRepositoryTagDo interface {
	gen.SubQuery
	Debug() IRegistryRepositoryTagDo
	WithContext(ctx context.Context) IRegistryRepositoryTagDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRegistryRepositoryTagDo
	WriteDB() IRegistryRepositoryTagDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRegistryRepositoryTagDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRegistryRepositoryTagDo
	Not(conds ...gen.Condition) IRegistryRepositoryTagDo
	Or(conds ...gen.Condition) IRegistryRepositoryTagDo
	Select(conds ...field.Expr) IRegistryRepositoryTagDo
	Where(conds ...gen.Condition) IRegistryRepositoryTagDo
	Order(conds ...field.Expr) IRegistryRepositoryTagDo
	Distinct(cols ...field.Expr) IRegistryRepositoryTagDo
	Omit(cols ...field.Expr) IRegistryRepositoryTagDo
	Join(table schema.Tabler, on ...field.Expr) IRegistryRepositoryTagDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryTagDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryTagDo
	Group(cols ...field.Expr) IRegistryRepositoryTagDo
	Having(conds ...gen.Condition) IRegistryRepositoryTagDo
	Limit(limit int) IRegistryRepositoryTagDo
	Offset(offset int) IRegistryRepositoryTagDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryRepositoryTagDo
	Unscoped() IRegistryRepositoryTagDo
	Create(values ...*entity.RegistryRepositoryTag) error
	CreateInBatches(values []*entity.RegistryRepositoryTag, batchSize int) error
	Save(values ...*entity.RegistryRepositoryTag) error
	First() (*entity.RegistryRepositoryTag, error)
	Take() (*entity.RegistryRepositoryTag, error)
	Last() (*entity.RegistryRepositoryTag, error)
	Find() ([]*entity.RegistryRepositoryTag, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryRepositoryTag, err error)
	FindInBatches(result *[]*entity.RegistryRepositoryTag, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.RegistryRepositoryTag) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRegistryRepositoryTagDo
	Assign(attrs ...field.AssignExpr) IRegistryRepositoryTagDo
	Joins(fields ...field.RelationField) IRegistryRepositoryTagDo
	Preload(fields ...field.RelationField) IRegistryRepositoryTagDo
	FirstOrInit() (*entity.RegistryRepositoryTag, error)
	FirstOrCreate() (*entity.RegistryRepositoryTag, error)
	FindByPage(offset int, limit int) (result []*entity.RegistryRepositoryTag, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRegistryRepositoryTagDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r registryRepositoryTagDo) Debug() IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Debug())
}

func (r registryRepositoryTagDo) WithContext(ctx context.Context) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r registryRepositoryTagDo) ReadDB() IRegistryRepositoryTagDo {
	return r.Clauses(dbresolver.Read)
}

func (r registryRepositoryTagDo) WriteDB() IRegistryRepositoryTagDo {
	return r.Clauses(dbresolver.Write)
}

func (r registryRepositoryTagDo) Session(config *gorm.Session) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Session(config))
}

func (r registryRepositoryTagDo) Clauses(conds ...clause.Expression) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r registryRepositoryTagDo) Returning(value interface{}, columns ...string) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r registryRepositoryTagDo) Not(conds ...gen.Condition) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r registryRepositoryTagDo) Or(conds ...gen.Condition) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r registryRepositoryTagDo) Select(conds ...field.Expr) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r registryRepositoryTagDo) Where(conds ...gen.Condition) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r registryRepositoryTagDo) Order(conds ...field.Expr) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r registryRepositoryTagDo) Distinct(cols ...field.Expr) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r registryRepositoryTagDo) Omit(cols ...field.Expr) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r registryRepositoryTagDo) Join(table schema.Tabler, on ...field.Expr) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r registryRepositoryTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r registryRepositoryTagDo) RightJoin(table schema.Tabler, on ...field.Expr) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r registryRepositoryTagDo) Group(cols ...field.Expr) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r registryRepositoryTagDo) Having(conds ...gen.Condition) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r registryRepositoryTagDo) Limit(limit int) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r registryRepositoryTagDo) Offset(offset int) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r registryRepositoryTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r registryRepositoryTagDo) Unscoped() IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Unscoped())
}

func (r registryRepositoryTagDo) Create(values ...*entity.RegistryRepositoryTag) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r registryRepositoryTagDo) CreateInBatches(values []*entity.RegistryRepositoryTag, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r registryRepositoryTagDo) Save(values ...*entity.RegistryRepositoryTag) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r registryRepositoryTagDo) First() (*entity.RegistryRepositoryTag, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryTag), nil
	}
}

func (r registryRepositoryTagDo) Take() (*entity.RegistryRepositoryTag, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryTag), nil
	}
}

func (r registryRepositoryTagDo) Last() (*entity.RegistryRepositoryTag, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryTag), nil
	}
}

func (r registryRepositoryTagDo) Find() ([]*entity.RegistryRepositoryTag, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RegistryRepositoryTag), err
}

func (r registryRepositoryTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RegistryRepositoryTag, err error) {
	buf := make([]*entity.RegistryRepositoryTag, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r registryRepositoryTagDo) FindInBatches(result *[]*entity.RegistryRepositoryTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r registryRepositoryTagDo) Attrs(attrs ...field.AssignExpr) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r registryRepositoryTagDo) Assign(attrs ...field.AssignExpr) IRegistryRepositoryTagDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r registryRepositoryTagDo) Joins(fields ...field.RelationField) IRegistryRepositoryTagDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r registryRepositoryTagDo) Preload(fields ...field.RelationField) IRegistryRepositoryTagDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r registryRepositoryTagDo) FirstOrInit() (*entity.RegistryRepositoryTag, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryTag), nil
	}
}

func (r registryRepositoryTagDo) FirstOrCreate() (*entity.RegistryRepositoryTag, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RegistryRepositoryTag), nil
	}
}

func (r registryRepositoryTagDo) FindByPage(offset int, limit int) (result []*entity.RegistryRepositoryTag, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r registryRepositoryTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r registryRepositoryTagDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r registryRepositoryTagDo) Delete(models ...*entity.RegistryRepositoryTag) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *registryRepositoryTagDo) withDO(do gen.Dao) *registryRepositoryTagDo {
	r.DO = *do.(*gen.DO)
	return r
}
