app:
  name: zpk-cli
  env: ${APP_ENV-release}
log:
  default:
    driver: stack
    channels:
      - console
  console:
    driver: console
    level: debug
setting:
  depot:
    oci_namespace: ${DEPOT_OCI_NAMESPACE-zpk_oci}