apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
  annotations:
    title: 制品库-镜像仓储
    w7.cc.app/title: 制品库-镜像仓储
    w7.cc/create-svc: 'false'
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      {{- include "registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        zpk.w7.cc/registry-jwt-rotate-nonce: {{ default "" .Values.global.registryJwt.rotateNonce | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "registry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "registry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh", "/etc/docker/registry/entrypoint.sh"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REGISTRY_AUTH_TOKEN_REALM
              value: https://{{ .Values.global.DOMAIN }}/zpk/v2/registry/auth
          volumeMounts:
            - mountPath: /etc/docker/registry/config.yml
              name: config-volume
              subPath: registry_config.yaml
            - mountPath: /etc/docker/registry/notify_config.yaml
              name: config-volume
              subPath: registry_notify_config.yaml
            - mountPath: /etc/docker/registry/entrypoint.sh
              name: config-volume
              subPath: entrypoint.sh
            - mountPath: /certs/registry-cert.pem
              name: registry-jwt-volume
              subPath: registry-cert.pem
            - mountPath: /certs/registry-key.pem
              name: registry-jwt-volume
              subPath: registry-key.pem
            - name: registry-storage
              mountPath: /var/lib/registry
              subPath: "registry"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "registry.fullname" . }}-config
        - name: registry-jwt-volume
          secret:
            secretName: {{ include "registry.jwtSecretName" . }}
        - name: registry-storage
          persistentVolumeClaim:
            claimName: {{ include "registry.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
