apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.global.cluster.storageRWMode }}
  storageClassName: {{  .Values.global.cluster.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.global.cluster.storageSize | quote }}