// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"github.com/w7panel/w7panel-zpk/common/accessor"
)

const TableNameRegistryUser = "ims_registry_user"

// RegistryUser mapped from table <ims_registry_user>
type RegistryUser struct {
	ID         int32                   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username   string                  `gorm:"column:username;not null" json:"username"`
	Password   string                  `gorm:"column:password;not null" json:"password"`
	Desc       string                  `gorm:"column:desc;not null" json:"desc"`
	Type       int32                   `gorm:"column:type;not null" json:"type"`
	ExpireDays int32                   `gorm:"column:expire_days;not null;default:-1" json:"expire_days"`
	Setting    *accessor.SettingOption `gorm:"column:setting;serializer:json" json:"setting"`
	Role       string                  `gorm:"column:role" json:"role"`
	CreatedAt  time.Time               `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time               `gorm:"column:updated_at" json:"updated_at"`
}

// TableName RegistryUser's table name
func (*RegistryUser) TableName() string {
	return TableNameRegistryUser
}
