// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"github.com/w7panel/w7panel-zpk/common/accessor"
)

const TableNameRegistryUserPermission = "ims_registry_user_permission"

// RegistryUserPermission mapped from table <ims_registry_user_permission>
type RegistryUserPermission struct {
	ID            int32                            `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID        int32                            `gorm:"column:user_id;not null" json:"user_id"`
	ResourceValue string                           `gorm:"column:resource_value;not null" json:"resource_value"`
	ResourceType  string                           `gorm:"column:resource_type;not null" json:"resource_type"`
	Action        *accessor.PermissionActionOption `gorm:"column:action;not null" json:"action"`
	CreatedAt     time.Time                        `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName RegistryUserPermission's table name
func (*RegistryUserPermission) TableName() string {
	return TableNameRegistryUserPermission
}
