// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameRegistryRepositoryDeployRule = "ims_registry_repository_deploy_rule"

// RegistryRepositoryDeployRule mapped from table <ims_registry_repository_deploy_rule>
type RegistryRepositoryDeployRule struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RepositoryID      int32     `gorm:"column:repository_id;not null" json:"repository_id"`
	DeployType        int32     `gorm:"column:deploy_type;not null;default:1" json:"deploy_type"`
	MatchType         int32     `gorm:"column:match_type;not null" json:"match_type"`
	TagName           string    `gorm:"column:tag_name;not null" json:"tag_name"`
	K8sConfig         string    `gorm:"column:k8s_config" json:"k8s_config"`
	K8sNamespace      string    `gorm:"column:k8s_namespace;not null" json:"k8s_namespace"`
	K8sControllerType string    `gorm:"column:k8s_controller_type;not null" json:"k8s_controller_type"`
	K8sAppName        string    `gorm:"column:k8s_app_name;not null" json:"k8s_app_name"`
	K8sContainerName  string    `gorm:"column:k8s_container_name;not null" json:"k8s_container_name"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	LatestTriggerAt   time.Time `gorm:"column:latest_trigger_at" json:"latest_trigger_at"`
}

// TableName RegistryRepositoryDeployRule's table name
func (*RegistryRepositoryDeployRule) TableName() string {
	return TableNameRegistryRepositoryDeployRule
}
