// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameTag = "ims_tag"

// Tag mapped from table <ims_tag>
type Tag struct {
	ID         int32        `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string       `gorm:"column:name;not null" json:"name"`
	TagFormula []TagFormula `gorm:"foreignKey:tag_id" json:"tag_formula"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
