// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameW7panelUser = "ims_w7panel_user"

// W7panelUser mapped from table <ims_w7panel_user>
type W7panelUser struct {
	ID              int32     `gorm:"column:id;primaryKey" json:"id"`
	W7panelUID      string    `gorm:"column:w7panel_uid;not null" json:"w7panel_uid"`
	W7panelUsername string    `gorm:"column:w7panel_username;not null" json:"w7panel_username"`
	UserUID         int32     `gorm:"column:user_uid;not null" json:"user_uid"`
	CreatedAt       time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName W7panelUser's table name
func (*W7panelUser) TableName() string {
	return TableNameW7panelUser
}
