// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameRegistryRepositoryDeployRuleMatchLog = "ims_registry_repository_deploy_rule_match_log"

// RegistryRepositoryDeployRuleMatchLog mapped from table <ims_registry_repository_deploy_rule_match_log>
type RegistryRepositoryDeployRuleMatchLog struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RuleID    int32     `gorm:"column:rule_id;not null" json:"rule_id"`
	ImageName string    `gorm:"column:image_name;not null" json:"image_name"`
	K8sLog    string    `gorm:"column:k8s_log" json:"k8s_log"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName RegistryRepositoryDeployRuleMatchLog's table name
func (*RegistryRepositoryDeployRuleMatchLog) TableName() string {
	return TableNameRegistryRepositoryDeployRuleMatchLog
}
