// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameVersion = "ims_version"

// Version mapped from table <ims_version>
type Version struct {
	ID                int32     `gorm:"column:id;primaryKey" json:"id"`
	FormulaID         int32     `gorm:"column:formula_id;not null" json:"formula_id"`
	Name              string    `gorm:"column:name;not null" json:"name"`
	Description       string    `gorm:"column:description;not null" json:"description"`
	PublishStatus     int32     `gorm:"column:publish_status" json:"publish_status"`
	PublishFailReason string    `gorm:"column:publish_fail_reason" json:"publish_fail_reason"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Version's table name
func (*Version) TableName() string {
	return TableNameVersion
}
