// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameFormulaSetting = "ims_formula_setting"

// FormulaSetting mapped from table <ims_formula_setting>
type FormulaSetting struct {
	ID                  int32                `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FormulaID           int32                `gorm:"column:formula_id;not null" json:"formula_id"`
	VersionID           int32                `gorm:"column:version_id;not null" json:"version_id"`
	SettingValueID      int32                `gorm:"column:setting_value_id;not null" json:"setting_value_id"`
	Type                int32                `gorm:"column:type;not null;default:1;comment:1为文件，2为配置" json:"type"` // 1为文件，2为配置
	Name                string               `gorm:"column:name;not null" json:"name"`
	FormulaSettingValue *FormulaSettingValue `gorm:"foreignKey:setting_value_id;references:id" json:"formula_setting_value"`
}

// TableName FormulaSetting's table name
func (*FormulaSetting) TableName() string {
	return TableNameFormulaSetting
}
