// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRegistryNamespace = "ims_registry_namespace"

// RegistryNamespace mapped from table <ims_registry_namespace>
type RegistryNamespace struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int32          `gorm:"column:user_id" json:"user_id"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	VisibleType int32          `gorm:"column:visible_type;not null;default:1" json:"visible_type"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName RegistryNamespace's table name
func (*RegistryNamespace) TableName() string {
	return TableNameRegistryNamespace
}
