// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameFormulaSettingValue = "ims_formula_setting_value"

// FormulaSettingValue mapped from table <ims_formula_setting_value>
type FormulaSettingValue struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Value string `gorm:"column:value;not null" json:"value"`
}

// TableName FormulaSettingValue's table name
func (*FormulaSettingValue) TableName() string {
	return TableNameFormulaSettingValue
}
