// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameOrder = "ims_order"

// Order mapped from table <ims_order>
type Order struct {
	ID                  int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID            int32      `gorm:"column:parent_id" json:"parent_id"`
	OrderSn             string     `gorm:"column:order_sn;not null" json:"order_sn"`
	UserID              int32      `gorm:"column:user_id" json:"user_id"`
	RemoteBuyerUID      int32      `gorm:"column:remote_buyer_uid" json:"remote_buyer_uid"`
	OrderType           int32      `gorm:"column:order_type" json:"order_type"`
	TotalFee            float64    `gorm:"column:total_fee;default:0.00" json:"total_fee"`
	BuyShop             string     `gorm:"column:buy_shop" json:"buy_shop"`
	FormulaID           int32      `gorm:"column:formula_id" json:"formula_id"`
	FormulaVersion      string     `gorm:"column:formula_version" json:"formula_version"`
	ProductType         int32      `gorm:"column:product_type" json:"product_type"`
	OutOrderSn          string     `gorm:"column:out_order_sn" json:"out_order_sn"`
	UsedTime            *time.Time `gorm:"column:used_time" json:"used_time"`
	ServiceExpireTime   int32      `gorm:"column:service_expire_time" json:"service_expire_time"`
	ServiceExpireTimeV2 *time.Time `gorm:"column:service_expire_time_v2" json:"service_expire_time_v2"`
	PayStatus           int32      `gorm:"column:pay_status" json:"pay_status"`
	PaidAt              *time.Time `gorm:"column:paid_at" json:"paid_at"`
	CreatedAt           time.Time  `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt           time.Time  `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
