package command

import "encoding/json"

func higressPluginDefaultConfig(name string) map[string]interface{} {
	rawConfig, exists := higressPluginDefaultConfigs[name]
	if !exists {
		return map[string]interface{}{}
	}
	config := map[string]interface{}{}
	if err := json.Unmarshal([]byte(rawConfig), &config); err != nil {
		panic(err)
	}
	return config
}

// Values come from configSchema.openAPIV3Schema.example in Higress Console's
// built-in plugin specs.
var higressPluginDefaultConfigs = map[string]string{
	"ai-agent":            `{"llm":{"apiKey":"xxxxxxxxxxxxxxxxxx","domain":"dashscope.aliyuncs.com","serviceName":"dashscope.dns","servicePort":443,"path":"/compatible-mode/v1/chat/completions","model":"qwen-max-0403","maxIterations":2},"promptTemplate":{"language":"CH"},"apis":[{"apiProvider":{"domain":"restapi.amap.com","serviceName":"geo.dns","servicePort":80,"apiKey":{"in":"query","name":"key","value":"xxxxxxxxxxxxxxx"},"api":"......\n"}}]}`,
	"ai-cache":            `{"embedding":{"type":"dashscope","serviceName":"my-dashscope.dns","apiKey":"your-api-key"},"vector":{"type":"dashvector","serviceName":"my-dashvector.dns","collectionID":"your-collection-id","serviceHost":"your-domain","apiKey":"your-api-key"},"cache":{"type":"redis","serviceName":"my-redis.dns","servicePort":6379,"timeout":100,"cacheTTL":300},"cacheKeyStrategy":"lastQuestion","enableSemanticCache":true,"cacheKeyFrom":"messages.@reverse.0.content","cacheValueFrom":"choices.0.message.content","cacheStreamValueFrom":"choices.0.delta.content","cacheToolCallsFrom":"choices.0.delta.content.tool_calls","responseTemplate":"{\"id\":\"from-cache\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"%s\"},\"finish_reason\":\"stop\"}],\"model\":\"from-cache\",\"object\":\"chat.completion\",\"usage\":{\"prompt_tokens\":0,\"completion_tokens\":0,\"total_tokens\":0}}\n","streamResponseTemplate":"data:{\"id\":\"from-cache\",\"choices\":[{\"index\":0,\"delta\":{\"role\":\"assistant\",\"content\":\"%s\"},\"finish_reason\":\"stop\"}],\"model\":\"from-cache\",\"object\":\"chat.completion\",\"usage\":{\"prompt_tokens\":0,\"completion_tokens\":0,\"total_tokens\":0}}\n\ndata:[DONE]\n"}`,
	"ai-data-masking":     `{"system_deny":true,"deny_openai":true,"deny_jsonpath":["$.messages[*].content"],"deny_message":"Question or answer contains sensitive words and has been blocked.","deny_words":["Custom Sensitive Word 1","Custom Sensitive Word 2"],"replace_roles":[{"regex":"%{MOBILE}","type":"replace","value":"****"},{"regex":"%{EMAILLOCALPART}@%{HOSTNAME:domain}","type":"replace","restore":true,"value":"****@$domain"},{"regex":"%{IP}","type":"replace","restore":true,"value":"***.***.***.***"},{"regex":"%{IDCARD}","type":"replace","value":"****"},{"regex":"sk-[0-9a-zA-Z]*","restore":true,"type":"hash"}]}`,
	"ai-history":          `{"redis":{"serviceName":"my-redis.dns","timeout":2000},"fillHistoryCnt":3,"cacheTTL":3600}`,
	"ai-intent":           `{"scene":{"category":"金融|电商|法律|Higress","prompt":"你是一个智能类别识别助手，负责根据用户提出的问题和预设的类别，确定问题属于哪个预设的类别，并给出相应的类别。用户提出的问题为:'%s',预设的类别为'%s'，直接返回一种具体类别，如果没有找到就返回'NotFound'。"},"llm":{"proxyServiceName":"intent-service.static","proxyUrl":"http://127.0.0.1:80/intent/compatible-mode/v1/chat/completions","proxyDomain":"127.0.0.1","proxyPort":"80","proxyModel":"qwen-long","proxyApiKey":"","proxyTimeout":"10000"}}`,
	"ai-json-resp":        `{"serviceName":"qwen","serviceDomain":"dashscope.aliyuncs.com","apiKey":["Your API Key"],"servicePath":"/compatible-mode/v1/chat/completions","jsonSchema":{"title":"ReasoningSchema","type":"object","properties":{"reasoning_steps":{"type":"array","items":{"type":"string"},"description":"The reasoning steps leading to the final conclusion."},"answer":{"type":"string","description":"The final answer, taking into account the reasoning steps."}},"required":["reasoning_steps","answer"],"additionalProperties":false}}`,
	"ai-load-balancer":    `{"lb_policy":"global_least_request","lb_config":{"serviceFQDN":"redis.static","servicePort":6379,"username":"default","password":"123456"}}`,
	"ai-prompt-decorator": `{"prepend":[{"role":"system","content":"请使用英语回答问题"}],"append":[{"role":"user","content":"每次回答完问题，尝试进行反问"}]}`,
	"ai-prompt-template":  `{"templates":[{"name":"developer-chat","template":{"model":"gpt-3.5-turbo","messages":[{"role":"system","content":"你是一个 {{program}} 专家，编程语言为 {{language}}"},{"role":"user","content":"帮我写一个 {{program}} 程序"}]}}]}`,
	"ai-proxy":            `{"provider":{"apiTokens":["YOUR_DASHSCOPE_API_TOKEN"],"modelMapping":{"*":"qwen-turbo"},"type":"qwen"}}`,
	"ai-quota":            `{"redis_key_prefix":"chat_quota:","admin_consumer":"consumer3","admin_path":"/quota","redis":{"service_name":"redis-service.default.svc.cluster.local","service_port":6379,"timeout":2000}}`,
	"ai-rag":              `{"dashscope":{"apiKey":"xxxxxxxxxxxxxxxxxxxx","serviceName":"dashscope","servicePort":443,"serviceHost":"dashscope.aliyuncs.com"},"dashvector":{"apiKey":"xxxxxxxxxxxxxxxxxxxx","serviceFQDN":"dashvector","servicePort":443,"serviceHost":"vrs-cn-xxxxxxxxxxxxxxxxxxxx.dashvector.cn-hangzhou.aliyuncs.com","topk":1,"threshold":0.4,"field":"raw"}}`,
	"ai-search":           `{"needReference":true,"searchFrom":[{"type":"quark","apiKey":"your-quark-api-key","serviceName":"quark.dns","servicePort":443},{"type":"google","apiKey":"your-google-api-key","cx":"your-search-engine-id","serviceName":"google.dns","servicePort":443},{"type":"bing","apiKey":"bing-key","serviceName":"bing.dns","servicePort":443},{"type":"arxiv","serviceName":"arxiv.dns","servicePort":443}],"searchRewrite":{"llmApiKey":"your-deepseek-api-key","llmModelName":"deepseek-chat","llmServiceName":"llm-deepseek.internal.dns","llmServicePort":443,"llmUrl":"https://api.deepseek.com/chat/completions"}}`,
	"ai-security-guard":   `{"serviceName":"safecheck.dns","servicePort":443,"serviceHost":"green-cip.cn-hangzhou.aliyuncs.com","accessKey":"XXXXXXXXX","secretKey":"XXXXXXXXXXXXXXX","checkRequest":true,"checkResponse":false}`,
	"ai-statistics":       `{"attributes":[{"key":"consumer","value_source":"request_header","value":"x-mse-consumer","apply_to_log":true,"apply_to_span":false},{"key":"question","value_source":"request_body","value":"messages.@reverse.0.content","apply_to_log":true,"apply_to_span":false},{"key":"answer","value_source":"response_streaming_body","value":"choices.0.delta.content","rule":"append","apply_to_log":true,"apply_to_span":false}]}`,
	"ai-token-ratelimit":  `{"rule_name":"default_rule","rule_items":[{"limit_by_per_ip":"from-remote-addr","limit_keys":[{"key":"0.0.0.0/0","token_per_minute":100}]}],"redis":{"service_name":"redis.static","service_port":6379,"username":"default","password":"123456"}}`,
	"ai-transformer":      `{"request":{"enable":false,"prompt":"如果请求path是以/httpbin开头的，帮我去掉/httpbin前缀，其他的不要改。"},"response":{"enable":true,"prompt":"帮我修改以下HTTP应答信息，要求：1. content-type修改为application/json；2. body由xml转化为json；3.移除content-length。"},"provider":{"serviceName":"qwen","domain":"dashscope.aliyuncs.com","sk":"sk-xxxxxxxxxxxxxxxxxxx"}}`,
	"basic-auth":          `{"global_auth":false,"consumers":[{"name":"consumer1","credential":"admin:123456"},{"name":"consumer2","credential":"guest:abc"}]}`,
	"bot-detect":          `{"blocked_code":404,"blocked_message":"resource not found"}`,
	"cache-control":       `{"suffix":"jpg|png|jpeg","expires":3600}`,
	"cors":                `{"allow_origins":["*"],"allow_methods":["*"],"allow_headers":["*"],"expose_headers":["*"],"allow_credentials":false,"max_age":7200}`,
	"custom-response":     `{"status_code":200,"headers":["Content-Type=application/json"],"body":"{\"hello\":\"world\"}"}`,
	"de-graphql":          `{"timeout":5000,"endpoint":"/graphql","domain":"api.github.com","gql":"query ($owner:String! $name:String!){\n   repository(owner:$owner, name:$name) {\n     name\n     forkCount\n     description\n  }\n}\n"}`,
	"ext-auth":            `{"http_service":{"endpoint_mode":"envoy","endpoint":{"service_name":"ext-auth.backend.svc.cluster.local","service_port":8090,"path_prefix":"/auth"},"timeout":1000}}`,
	"frontend-gray":       `{"grayKey":"userid","rules":[{"name":"inner-user","grayKeyValue":["00000001","00000005"]},{"name":"beta-user","grayKeyValue":["00000002","00000003"],"grayTagKey":"level","grayTagValue":["level3","level5"]}],"baseDeployment":{"version":"base"},"grayDeployments":[{"name":"beta-user","version":"gray","enabled":true}]}`,
	"geo-ip":              `{"ip_protocol":"ipv4","ip_source_type":"header","ip_header_name":"X-Real-Ip"}`,
	"hmac-auth":           `{"global_auth":false,"consumers":[{"key":"appKey-example-1","secret":"appSecret-example-1","name":"consumer-1"},{"key":"appKey-example-2","secret":"appSecret-example-2","name":"consumer-2"}]}`,
	"ip-restriction":      `{"ip_source_type":"origin-source","allow":["10.0.0.1","192.168.0.0/16"]}`,
	"jwt-auth":            `{"global_auth":false,"consumers":[{"name":"consumer1","issuer":"abcd","jwks":"{\n  \"keys\": [\n    {\n      \"kty\": \"oct\",\n      \"kid\": \"123\",\n      \"k\": \"hM0k3AbXBPpKOGg__Ql2Obcq7s60myWDpbHXzgKUQdYo7YCRp0gUqkCnbGSvZ2rGEl4YFkKqIqW7mTHdj-bcqXpNr-NOznEyMpVPOIlqG_NWVC3dydBgcsIZIdD-MR2AQceEaxriPA_VmiUCwfwL2Bhs6_i7eolXoY11EapLQtutz0BV6ZxQQ4dYUmct--7PLNb4BWJyQeWu0QfbIthnvhYllyl2dgeLTEJT58wzFz5HeNMNz8ohY5K0XaKAe5cepryqoXLhA-V-O1OjSG8lCNdKS09OY6O0fkyweKEtuDfien5tHHSsHXoAxYEHPFcSRL4bFPLZ0orTt1_4zpyfew\",\n      \"alg\": \"HS256\"\n    }\n  ]\n}\n"}]}`,
	"key-auth":            `{"global_auth":false,"consumers":[{"credential":"key-example1","name":"consumer1"},{"credential":"key-example2","name":"consumer2"}],"keys":["apikey"],"in_query":true}`,
	"key-rate-limit":      `{"limit_by_header":"x-api-key","limit_keys":[{"key":"example-key-a","query_per_second":10},{"key":"example-key-b","query_per_minute":1000}]}`,
	"mcp-server":          `{"server":{"name":"rest-amap-server","config":{"apiKey":"your-api-key-here"},"allowTools":["maps-geo"]},"tools":[{"name":"maps-geo","description":"Convert structured address information to latitude and longitude coordinates.","args":[{"name":"address","description":"The structured address to parse","type":"string","required":true,"position":"query"},{"name":"city","description":"The city to search in","type":"string","required":false,"position":"query"},{"name":"output","description":"Output format","type":"string","enum":["json","xml"],"default":"json","position":"query"}],"requestTemplate":{"url":"https://restapi.amap.com/v3/geocode/geo","method":"GET","headers":[{"key":"x-api-key","value":"{{.config.apiKey}}"}]},"responseTemplate":{"body":"# Geocoding Information\n{{- range $index, $geo := .geocodes }}\n## Location {{add $index 1}}\n- **Country**: {{ $geo.country }}\n- **Province**: {{ $geo.province }}\n- **City**: {{ $geo.city }}\n- **Coordinates**: {{ $geo.location }}\n{{- end }}\n"}}]}`,
	"model-mapper":        `{"modelMapping":{"gpt-4-*":"qwen-max","gpt-4o":"qwen-vl-plus","*":"qwen-turbo"}}`,
	"model-router":        `{"addProviderHeader":"x-higress-llm-provider","modelToHeader":"x-higress-llm-model"}`,
	"oauth":               `{"global_auth":false,"consumers":[{"name":"consumer1","client_id":"12345678-xxxx-xxxx-xxxx-xxxxxxxxxxxx","client_secret":"abcdefgh-xxxx-xxxx-xxxx-xxxxxxxxxxxx"},{"name":"consumer2","client_id":"87654321-xxxx-xxxx-xxxx-xxxxxxxxxxxx","client_secret":"hgfedcba-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}]}`,
	"oidc":                `{"redirect_url":"http://foo.bar.com/oauth2/callback","oidc_issuer_url":"https://dev-o43xb1mz7ya7ach4.us.auth0.com/","client_id":"XXXXXXXXXXXXXXXX","client_secret":"XXXXXXXXXXXXXXXX","scope":"openid email offline_access","cookie_secret":"nqavJrGvRmQxWwGNptLdyUVKcBNZ2b18Guc1n_8DCfY=","service_name":"auth.dns","service_port":443,"match_type":"whitelist","match_list":[{"match_rule_domain":"*.bar.com","match_rule_path":"/foo","match_rule_type":"prefix"}]}`,
	"opa":                 `{"serviceSource":"k8s","serviceName":"opa","servicePort":8181,"namespace":"higress-backend","policy":"example1","timeout":"5s"}`,
	"request-block":       `{"blocked_code":404,"block_urls":["swagger.html"],"block_headers":["example-key","example-value"],"block_bodies":["hello world"],"case_sensitive":false}`,
	"request-validation":  `{"body_schema":{"type":"object","required":["boolean_payload"],"properties":{"boolean_payload":{"type":"boolean"}}},"rejected_code":403,"rejected_msg":"请求被拒绝"}`,
	"traffic-tag":         `{"conditionGroups":[{"headerName":"x-mse-tag","headerValue":"gray","logic":"and","conditions":[{"conditionType":"header","key":"role","operator":"not_in","value":["user","viewer","editor"]}]}]}`,
	"transformer":         `{"reqRules":[{"operate":"remove","headers":[{"key":"X-remove"}]}],"respRules":[{"operate":"add","body":[{"key":"foo.bar","value":"value"}]}]}`,
	"waf":                 `{"useCRS":true,"secRules":["SecDebugLogLevel 3","SecRuleEngine On","SecAction \"id:100,phase:1,pass\"","SecRule REQUEST_URI \"@streq /admin\" \"id:101,phase:1,t:lowercase,deny\"","SecRule REQUEST_BODY \"@rx maliciouspayload\" \"id:102,phase:2,t:lowercase,deny\""]}`,
}
